*CMZ :          20/09/2026  09.36.38  by  Michael Scheer
*CMZ :  4.02/00 17/09/2025  10.02.56  by  Michael Scheer
*CMZ :  4.01/00 09/01/2023  20.52.32  by  Michael Scheer
*CMZ :  4.00/14 22/12/2021  13.31.15  by  Michael Scheer
*CMZ :  4.00/13 20/12/2021  16.32.19  by  Michael Scheer
*CMZ :  4.00/11 22/04/2021  18.57.39  by  Michael Scheer
*CMZ :  4.00/06 09/12/2019  14.35.09  by  Michael Scheer
*CMZ :  4.00/04 23/08/2019  15.23.40  by  Michael Scheer
*CMZ :  3.03/00 17/08/2015  10.09.12  by  Michael Scheer
*CMZ :  3.02/05 08/06/2015  13.40.53  by  Michael Scheer
*CMZ :  3.02/04 18/03/2015  09.33.03  by  Michael Scheer
*CMZ :  3.02/00 24/09/2014  11.52.00  by  Michael Scheer
*CMZ :  3.01/07 23/06/2014  13.59.37  by  Michael Scheer
*CMZ :  3.01/05 13/06/2014  11.42.17  by  Michael Scheer
*CMZ :  3.00/00 11/03/2013  15.13.36  by  Michael Scheer
*CMZ :  2.70/06 03/01/2013  13.47.56  by  Michael Scheer
*CMZ :  2.70/05 02/01/2013  15.31.59  by  Michael Scheer
*CMZ :  2.70/00 08/11/2012  12.29.49  by  Michael Scheer
*CMZ :  2.68/05 25/10/2012  15.10.37  by  Michael Scheer
*CMZ :  2.68/02 26/06/2012  11.55.39  by  Michael Scheer
*CMZ :  2.67/01 01/03/2012  16.47.26  by  Michael Scheer
*CMZ :  2.67/00 17/02/2012  13.32.15  by  Michael Scheer
*CMZ :  2.63/05 03/08/2009  08.58.29  by  Michael Scheer
*CMZ :  2.41/13 15/03/2007  11.13.54  by  Michael Scheer
*CMZ :  2.41/10 14/08/2002  17.34.01  by  Michael Scheer
*CMZ :  1.00/00 24/09/97  17.11.48  by  Michael Scheer
*CMZ : 00.01/09 06/10/95  10.20.31  by  Michael Scheer
*CMZ : 00.01/08 18/07/95  10.46.26  by  Michael Scheer
*CMZ : 00.01/04 30/01/95  16.00.05  by  Michael Scheer
*CMZ : 00.00/00 28/04/94  16.12.29  by  Michael Scheer
*-- Author : Michael Scheer
      SUBROUTINE HISEND
*KEEP,gplhint.
!******************************************************************************
!
!      Copyright 2013 Helmholtz-Zentrum Berlin (HZB)
!      Hahn-Meitner-Platz 1
!      D-14109 Berlin
!      Germany
!
!      Author Michael Scheer, Michael.Scheer@Helmholtz-Berlin.de
!
! -----------------------------------------------------------------------
!
!    This program is free software: you can redistribute it and/or modify
!    it under the terms of the GNU General Public License as published by
!    the Free Software Foundation, either version 3 of the License, or
!    (at your option) any later version.
!
!    This program is distributed in the hope that it will be useful,
!    but WITHOUT ANY WARRANTY; without even the implied warranty of
!    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!    GNU General Public License for more details.
!
!    You should have received a copy (wave_gpl.txt) of the GNU General Public
!    License along with this program.
!    If not, see <http://www.gnu.org/licenses/>.
!
!    Dieses Programm ist Freie Software: Sie koennen es unter den Bedingungen
!    der GNU General Public License, wie von der Free Software Foundation,
!    Version 3 der Lizenz oder (nach Ihrer Option) jeder spaeteren
!    veroeffentlichten Version, weiterverbreiten und/oder modifizieren.
!
!    Dieses Programm wird in der Hoffnung, dass es nuetzlich sein wird, aber
!    OHNE JEDE GEWAEHRLEISTUNG, bereitgestellt; sogar ohne die implizite
!    Gewaehrleistung der MARKTFAEHIGKEIT oder EIGNUNG FueR EINEN BESTIMMTEN ZWECK.
!    Siehe die GNU General Public License fuer weitere Details.
!
!    Sie sollten eine Kopie (wave_gpl.txt) der GNU General Public License
!    zusammen mit diesem Programm erhalten haben. Wenn nicht,
!    siehe <http://www.gnu.org/licenses/>.
!
!******************************************************************************
*KEND.

C--- TERMINATES HBOOK AND WRITE HISTOS TO FILE

*KEEP,TRACKF90U.
      USE TRACKF90
*KEEP,SPECTF90U.
      USE SPECTF90

*KEEP,SOURCEF90U.

      USE SOURCEF90

*KEEP,OBSERVF90U.

	USE OBSERVF90
*KEEP,REARGF90U.

	USE REARGF90
*KEEP,WFOLDF90U.

	USE WFOLDF90
*KEEP,AFREQF90U.

	USE AFREQF90
*KEEP,AMPLIF90U.

	USE AMPLIF90
*KEND.

      use bunchmod
      use mhbook_mod

      IMPLICIT NONE

*KEEP,CMPARA.

      INTEGER LIDIMP,NOMDIMP,IBFDIM4P,IBFDIM2P,NXPANP,NYPANP
      INTEGER NBTABP,NDMASHZP,NDMASHYP,MAXFOUR,NFOURD

      INTEGER NWMAXP,NDFREQP,NDOBSVP,NDARGUP,NDWSOUP
      INTEGER NGCOEFP,NDOBSVZP,NDOBSVYP,NSPLINEP,NDPOLP,NDSPARP

      INTEGER N3DPOIP,N2DHPOIP,NPHPOIP


      PARAMETER (LIDIMP=501)    ! MAX. NUMBER OF SOURCES
      PARAMETER (NDPOLP=101)    ! MAX. NUMBER OF POLES
                                ! IN SR BEAMPOW POLES MAY BE SPLITTED, I.E.
                                ! NUMBER OF POLES ARE NOT NUMBER OF
                                ! HARDWAREPOLES
      !
      PARAMETER (NWMAXP=2**15)    !NUMBER OF POINTS OF REFERENCE ORBIT
      PARAMETER (NDFREQP=1100001)    !NUMBER OF FREQUENCES FOR SPECTRUM-CALCULATION
      PARAMETER (NDSPARP=1024)   !TO HAVE SOME SPARE IN BUFFER
      PARAMETER (NDWSOUP=NDSPARP+1024)!NUMBER OF STEPS PER SOURCE OF
                                      !(MINI-TRAJEKTORY)
               !SEE ALSO PARAMETER NBADDP IN SOURCE.CMN
               !FOR INTEGRATION BUFFER IN SR SPECTRUM
      !
      PARAMETER (NDARGUP=NDSPARP+1024)!NUMBER OF INTEGRATION STEPS PER SOURCE
                                      !MUST BE LOWER OR EQUAL NDWSOUP
      !
      PARAMETER (NDOBSVZP=2048)    !NUMBER OF OBSERVATION POINTS IN Z-DIRECTION
      ! SAME FOR Z AND Y, OR PROBLEMS...
      PARAMETER (NDOBSVYP=NDOBSVZP)    !NUMBER OF OBSERVATION POINTS IN Y-DIRECTION
      PARAMETER (NDOBSVP=NDOBSVZP*NDOBSVYP) !NUMBER OF OBSERVATION POINTS
      PARAMETER (NSPLINEP=NDOBSVZP+NDOBSVYP)!FOR SR FSPLINE

      PARAMETER (NGCOEFP=32)         !NUMBER FOURIER COEFFICIENT FOR GAUSSIAN FOR
      !                                !FOLDING PROCEDURE
      PARAMETER (NDMASHZP=NDOBSVZP/2)   !NUMBER OF ADJACENT MASHES FOR FOLDING
      PARAMETER (NDMASHYP=NDOBSVYP/2)   !NUMBER OF ADJACENT MASHES FOR FOLDING

      PARAMETER(MAXFOUR=2**15)  !NUMBER OF FOURIER COEFFICIENTS FOR B-FIELD
      PARAMETER (NFOURD=2*MAXFOUR) !NUMBER OF FOURIER COEFFICIENTS FOR SR FOURWLS

      INTEGER NBMESSXP,NBMESSYP,NBMESSZP
      PARAMETER (NBMESSXP=3,NBMESSYP=3,NBMESSZP=3)

      PARAMETER(N3DPOIP=NBMESSXP*NBMESSYP*NBMESSZP) !NUMBER DATA POINTS FOR BPOLY3D
      PARAMETER(N2DHPOIP=NBMESSXP*NBMESSYP*NBMESSZP) !NUMBER DATA POINTS FOR BPOLY3D
      PARAMETER(NPHPOIP=NBMESSXP*NBMESSYP*NBMESSZP) !NUMBER DATA POINTS FOR BPOLY3D

      INTEGER NLIOBFRP,NOBFRP,NLIFRP,NLIOBZP,NLIOBP
      INTEGER ILIOB,ILIOBFR,IOBFR,ILIOBZ,ILIFR,IFROB
        PARAMETER (NLIOBFRP=600000)  !GENERAL DIMENSION OF SPECTRUM ARRAYS
      PARAMETER (NLIOBP=NLIOBFRP)
      PARAMETER (NLIOBZP=NLIOBFRP)
      PARAMETER (NOBFRP=NLIOBFRP)
      PARAMETER (NLIFRP=NLIOBFRP)

C------------ OLD STUFF (??) --------------------------------

      PARAMETER (NOMDIMP=1)   ! MAX. ANZAHL VON FREQUENZEN IM SPEKTRUM
      PARAMETER (IBFDIM4P=1)    ! BUFFER GROESSE FUER RBUFF4,IBUFF4
      PARAMETER (IBFDIM2P=8)    ! BUFFER GROESSE FUER RBUFF2
      PARAMETER (NXPANP=1)      ! PANDIRA X-DIMENSION
      PARAMETER (NYPANP=1)      ! PANDIRA Y-DIMENSION
      PARAMETER (NBTABP=2**14+2**13)   ! BTAB DIMENSION

c20180509      REAL*4 RBUFF4(4,IBFDIM4P)
c      REAL*4 RBUFF2(2,IBFDIM2P)
c      INTEGER IBUFF4(4,IBFDIM4P)
c      INTEGER IBUFF2(2,IBFDIM2P)
c      EQUIVALENCE (RBUFF4(1,1),IBUFF4(1,1)),(RBUFF2(1,1),IBUFF2(1,1))
c      COMMON/BUFCOM/RBUFF4,RBUFF2,ILIOB,ILIOBFR,IOBFR,ILIOBZ,ILIFR,IFROB
*KEEP,CONTRL.
      DOUBLE PRECISION ECPHOTON,XSTART,XINTER,XSTOP,XIANF,XIEND,GWINFC,BL0CUT,BL0HYS
     &  ,DMYGAMMA,DMYBETA,VXIN,VYIN,DMYCUR,BANWID,D1MBETA
     &  ,VZIN,YSTART,ZSTART,DEVLEN,DEVLEN2,DMYENERGY,GMOM,EMOM
     &  ,XSTARTH,XSTOPH,DBRHO,BMOVECUT
     &  ,BXSTART,BYSTART,BZSTART,AXSTART,AYSTART,AZSTART
     &  ,BXSTOP,BYSTOP,BZSTOP,AXSTOP,AYSTOP,AZSTOP,XBSYM

      INTEGER       LIDIM,NBDIM,NOMDIM,IBFDIM4,IBFDIM2,IANZPL,LUNGFI,
     &  LUNGFO,IWFILSP0,IWFILSPF,IWFILPOW,
     &  NXPAN,NYPAN,
     &  ICODE,KOUT,KBFELD,KHALBA,KHALBASY,KUNDUGAP,KBEXTERN,KBAMWLS,
     &  IRFILF,IBGAUSS,KCIRC,
     &  KSIGN,ICHECK,KBETAX,IFORM0,IFORM,
     &  IWFILB0,IRFILB0,IWFILF,IWSECTMAGS,IRFILP,IRFILB,ITRAKT,
     &  IWFILT0,IRFILT0,IWFILL0,IRFILL0,
     &  IEXPL0,NLPOI,IWFILL,IWFILA,IRFILA,ISAVLO,
     &  IOPTIC,IGENFUN,IDISPER,IEMIT,IERZANA,IEMIAHW,
     &  IBHARD,IERZFUN,IRANDO,IBHTRACK,IBHELM,KBGENESIS,ISPLINE,
     &  IBSYM,IWLSOPT,IKBFORM,IRBTAB,NBTAB,IJUST,MYINUM,NSTEPMX,
     &  ICTEST ,IHFOLD,IBSYMY,IBSYMZ,
     &  NWMAX,ISPEC,IVELOFIELD,NDFREQ,NDOBSV,IFREQ2P,IWFILINT,JWFILINT,
     &  IHPIN,
     &  NDPAWC,IPIN,IPOLA,ifold,ibunch,ISPECANA,NGCOEF,ISPECMODE,
     &  NDMASHZ,NDMASHY,NDOBSVZ,NDOBSVY,ISIGUSR,ISPECINT,
     &  IPINALL,IHBOOK,IHINDEX,
     &  IHTRACK,IHTRSMP,IHTRACKM,IHBETA,IUNIT,IUNITS,IF1DIM,IHFREQ,
     &  IPOWER,NDPOL,IBEAMPOL,KUCROSS,KMAGSEQ,IMGSQF,KMAGCOR,
     &  IWBTAB,IABEND,irbmap6,iwbmap,
     &  IWFILFL0,IWFILFLF,IRPHI,
     &  IUSEM,IPINCIRC,ISTOKES,irbtabzy,ifourbtabzy,IRBTABXYZ,ISPECANAF,IBRILL,
     &  IWFILSTO,IWFLSTOF,IWFLSTOE,IWFLSTOEF,IRFILSP0,IRFILSTO,ISPECSUM,
     &  IWFILS,IWFILSF,IWFILSE,IWFILSEF,
     &  IWFILB,IWFILBF,IWFILBE,IWFILBEF,
     &  IWFILBRILL,IWFILBRILLF,IWFILBRILLE,IWFILBRILLEF,
     &  KELLIP,IWFILRAY,KELLANA,
     &  IPHASE,IDOSE,IPHOTON,IEFOLD,IDESYNC,ISPECDIP,
     &  IUOUT,IUNAME,IUSTEP,IPHASEANA,
     &  KBPOLYH,IGFLOAT
     &  ,KBPOLY3D,IWBPOLY3D
     &  ,KBPOLY2DH,IWBPOLY2DH
     &  ,KBPharm,IWBpharm
     &  ,KBREC,KBPOLYMAG,IBATCH,kbundumag,kbundumap,kbunduverb
     &  ,IMAGSPLN,IHINPUT,IHOUTP,IMHBCOM,IMAGJOB
     &  ,IW_BLEN,IW_BLENF,IW_CIRC
     &  ,IHLIMIT_C,IHISINI_C,ihisascii,iroottrees,IBFORCE
     &  ,iampli,kampli,IAMPJIT,IUNDULATOR,IWIGGLER,IEXPERT,IBSUPER,IBERROR
     &  ,ieneloss,iefield,iroothdf5,nocern,iadjust,iwarnbmap,iwarnmyb,mthreads,igenpho

      CHARACTER(65) CODE
      CHARACTER     CHISASCII

      COMMON/CONTRL/ECPHOTON,
     &  XSTART,XINTER,XSTOP,XIANF,XIEND,GWINFC,BL0CUT,BL0HYS
     &  ,DMYGAMMA,DMYBETA,VXIN,VYIN,DMYCUR,BANWID,D1MBETA
     &  ,VZIN,YSTART,ZSTART,DEVLEN,DEVLEN2,DMYENERGY,GMOM,EMOM
     &  ,XSTARTH,XSTOPH,DBRHO,BMOVECUT
     &  ,BXSTART,BYSTART,BZSTART,AXSTART,AYSTART,AZSTART
     &  ,BXSTOP,BYSTOP,BZSTOP,AXSTOP,AYSTOP,AZSTOP,XBSYM
     &  ,LIDIM,NBDIM,NOMDIM,IBFDIM4,IBFDIM2,IANZPL,LUNGFI,
     &  LUNGFO,IWFILSP0,IWFILSPF,IWFILPOW,
     &  NXPAN,NYPAN,
     &  ICODE,KOUT,KBFELD,KHALBA,KHALBASY,KUNDUGAP,KBEXTERN,KBAMWLS,
     &  IRFILF,IBGAUSS,KCIRC,
     &  KSIGN,ICHECK,KBETAX,IFORM0,IFORM,
     &  IWFILB0,IRFILB0,IWFILF,IWSECTMAGS,IRFILP,IRFILB,ITRAKT,
     &  IWFILT0,IRFILT0,IWFILL0,IRFILL0,
     &  IEXPL0,NLPOI,IWFILL,IWFILA,IRFILA,ISAVLO,
     &  IOPTIC,IGENFUN,IDISPER,IEMIT,IERZANA,IEMIAHW,
     &  IBHARD,IERZFUN,IRANDO,IBHTRACK,IBHELM,KBGENESIS,ISPLINE,
     &  IBSYM,IWLSOPT,IKBFORM,IRBTAB,NBTAB,IJUST,MYINUM,NSTEPMX,
     &  ICTEST ,IHFOLD,IBSYMY,IBSYMZ,
     &  NWMAX,ISPEC,IVELOFIELD,NDFREQ,NDOBSV,IFREQ2P,IWFILINT,JWFILINT,
     &  IHPIN,
     &  NDPAWC,IPIN,IPOLA,ifold,ibunch,ISPECANA,NGCOEF,ISPECMODE,
     &  NDMASHZ,NDMASHY,NDOBSVZ,NDOBSVY,ISIGUSR,ISPECINT,
     &  IPINALL,IHBOOK,IHINDEX,
     &  IHTRACK,IHTRSMP,IHTRACKM,IHBETA,IUNIT,IUNITS,IF1DIM,IHFREQ,
     &  IPOWER,NDPOL,IBEAMPOL,KUCROSS,KMAGSEQ,KMAGCOR,IMGSQF,
     &  IWBTAB,IABEND,irbmap6,iwbmap,
     &  IWFILFL0,IWFILFLF,IRPHI,
     &  IUSEM,IPINCIRC,ISTOKES,irbtabzy,ifourbtabzy,IRBTABXYZ,ISPECANAF,IBRILL,
     &  IWFILSTO,IWFLSTOF,IWFLSTOE,IWFLSTOEF,IRFILSP0,IRFILSTO,ISPECSUM,
     &  KELLIP,IWFILRAY,KELLANA,
     &  IPHASE,IDOSE,IPHOTON,IEFOLD,IDESYNC,ISPECDIP,IPHASEANA,
     &  IUOUT,IUNAME,IUSTEP,
     &  KBPOLYH,IGFLOAT
     &  ,KBPOLY3D,IWBPOLY3D
     &  ,KBPOLY2DH,IWBPOLY2DH,
     &  KBPharm,IWBpharm,
     &  IWFILS,IWFILSF,IWFILSE,IWFILSEF,
     &  IWFILB,IWFILBF,IWFILBE,IWFILBEF,
     &  IWFILBRILL,IWFILBRILLF,IWFILBRILLE,IWFILBRILLEF
     &  ,KBREC,KBPOLYMAG,IBATCH,kbundumag,kbundumap,kbunduverb
     &  ,IMAGSPLN,IHINPUT,IHOUTP,IMHBCOM, IMAGJOB
     &  ,IW_BLEN,IW_BLENF,IW_CIRC
     &  ,IHLIMIT_C,IHISINI_C,ihisascii,iroottrees,IBFORCE
     &  ,iampli,kampli,IAMPJIT,IUNDULATOR,IWIGGLER,IEXPERT,IBSUPER,IBERROR
     &  ,ieneloss,iefield,iroothdf5,iwarnbmap,iwarnmyb,mthreads,igenpho
     &  ,CODE,CHISASCII


      NAMELIST/CONTRL/CODE,ECPHOTON,MYINUM,NSTEPMX,DMYENERGY,VXIN,VYIN,VZIN,BMOVECUT
     &  ,KBFELD,KHALBA,KHALBASY,KUNDUGAP,IRFILF,IRBTAB,
     &  KBEXTERN,KBAMWLS,IBGAUSS,KCIRC,IRPHI,
     &  xstart,XINTER,xstop,xianf,xiend,
     &  KSIGN,ICHECK,KBETAX,IFORM0,IFORM,
     &  IWFILB0,IRFILB0,IWFILF,IWSECTMAGS,IRFILP,IRFILB,ITRAKT,
     &  IWFILT0,IRFILT0,IWFILL0,GWINFC,BL0CUT,BL0HYS,
     &  IRFILL0,
     &  IEXPL0,NLPOI,IWFILL,IWFILA,IRFILA,ISAVLO,IOPTIC,
     &  IBHARD,IERZFUN,IERZANA,IGENFUN,
     &  IRANDO,IBHTRACK,IBHELM,KBGENESIS,ISPLINE,IDISPER,
     &  IBSYM,XBSYM,IWLSOPT,IKBFORM,IJUST,IBSYMY,IBSYMZ
     &  ,YSTART,ZSTART,DMYCUR,BANWID
     &  ,ICTEST,IEMIT,IEMIAHW,IHFOLD
     &  ,ISPEC,IVELOFIELD,IWFILSP0,IFREQ2P,IWFILINT,JWFILINT,IWFILSPF
     &  ,IWFILPOW
     &  ,IHPIN,IPOLA,ifold,ibunch,IPIN,ISPECANA,ISIGUSR,ISPECINT,ISPECMODE
     &  ,IPINALL,IHINDEX
     &  ,IHTRACK,IHTRSMP,IHTRACKM,IHBETA,IUNIT,IUNITS,IF1DIM,IHFREQ
     &  ,XSTARTH,XSTOPH,IPOWER,IBEAMPOL,KUCROSS,KMAGSEQ,KMAGCOR,IMGSQF,
     &  IWBTAB,irbmap6,iwbmap
     &  ,IWFILFL0,IWFILFLF
     &  ,IUSEM,IPINCIRC,ISTOKES,irbtabzy,ifourbtabzy,IRBTABXYZ,ISPECANAF,IBRILL
     &  ,IWFILSTO,IWFLSTOF,IWFLSTOE,IWFLSTOEF,IRFILSP0,IRFILSTO,ISPECSUM
     &  ,KELLIP,IWFILRAY,KELLANA
     &  ,IPHASE,IDOSE,IPHOTON,IEFOLD,IDESYNC,ISPECDIP,IPHASEANA
     &  ,IUOUT,IUNAME,IUSTEP
     &  ,KBPOLYH
     &  ,KBPOLY3D,IWBPOLY3D
     &  ,KBPOLY2DH,IWBPOLY2DH,
     &  KBPharm,IWBpharm,
     &  IWFILS,IWFILSF,IWFILSE,IWFILSEF,
     &  IWFILB,IWFILBF,IWFILBE,IWFILBEF,
     &  IWFILBRILL,IWFILBRILLF,IWFILBRILLE,IWFILBRILLEF
     &  ,KBREC,KBPOLYMAG,kbundumag,kbundumap,kbunduverb
     &  ,IMAGSPLN,IHINPUT,IHOUTP,IMHBCOM, ihisascii,iroottrees,
     &  ieneloss,iefield,iroothdf5,
     &  iampli,kampli,IAMPJIT,IUNDULATOR,IWIGGLER,IEXPERT,IBSUPER,IBERROR,ibforce,
     &  nocern,iadjust,mthreads,igenpho,
     &  CHISASCII
*KEEP,MYFILES.
      CHARACTER(128) FILEB0,FILET0,FILEL0,FILEL,FILEA,FILEP,FILEO,FILECOD,
     &  FILEH,FILED,FILEF,FILETB,FILEJ,FILETR,FILEI,FILEBE
     &  ,FILEFR,FILEOB,FILEGFO,FILESP0,FILEINT,FILEHB
     &  ,FILEWB,FILEZZPYYP,FILESPF,FILEWBT,FILEPOW
     &  ,FILEABS,FILEMG,FILEFF
     &  ,FILEFL0,FILEFLF,filetbx
     &  ,FILETBZ,FILESTO,FILESTOF,FILESTOE,FILESTOEF,FILERAY
     &  ,FILEAM,FILEAMO
     &  ,FILES,FILESE,FILESF,FILESEF
     &  ,FILEC,FILECE,FILECF,FILECEF
     &  ,FILEBRILL,FILEBRILLE,FILEBRILLF,FILEBRILLEF
     &  ,FILEREC,FILEBMAP
     &  ,FILE3DCOE,FILE3DFIT
     &  ,FILE2DHFIT
     &  ,FILEPHFIT
     &  ,FILEPH,FILEAMPLI,FILEFTH,FILEFTV,FILEGENL,FILEGENI

C5.10.95      REAL*4 B(NBDIMP,3,3,3),RB(NBDIMP,3)
      REAL*4 DYB0,DZB0

      INTEGER LUNB0,NXB0,NYB0,NZB0,LUNT0,LUNL0,LUNL,LUNA,LUNP,LUNO,
     &  LUND,LUNCOD,LUNH,LUNF,LUNTB,LUNJ,LUNTR,LUNBE
     &  ,LUNOB,LUNFR,LUNSP0,LUNINT,LUNHB,LUNWB,LUNZZPYYP
     &  ,LUNSPF,LUNWBT
     &  ,LUNABS,LUNMG,LUNEFF
     &  ,LUNFL0,LUNFLF
     &  ,LUNTBZ,LUNSTO,LUNSTOF,LUNRAY
     &  ,LUNAM,LUNAMO
     &  ,LUNS,LUNSE,LUNSF,LUNSEF
     &  ,LUNC,LUNCE,LUNCF,LUNCEF,LUNREC,LUNBMAP
     &  ,LUN3DCOE,LUN3DFIT
     &  ,LUN2DHFIT
     &  ,LUNPHFIT
     &  ,LUNPH,LUNAMPLI,LUNFT,LUNPOW,LUNGENL,LUNGENI

      COMMON/MYFILES/FILEB0,LUNB0,DYB0,DZB0,NXB0,NYB0,NZB0,
     &  FILET0,LUNT0,FILEL0,LUNL0,
     &  FILEL,LUNL,FILEA,LUNA,
     &  FILEP,LUNP,FILEO,LUNO,FILED,LUND,
     &  FILECOD,LUNCOD,
     &  FILEH,LUNH,
     &  FILEF,LUNF,
     &  FILETB,LUNTB
     &  ,FILEJ,LUNJ
     &  ,FILETR,LUNTR,FILEI,FILEGFO,FILEBE,LUNBE
     &  ,FILEOB,LUNOB
     &  ,FILEFR,LUNFR
     &  ,FILESP0,LUNSP0
     &  ,FILEPOW,LUNPOW
     &  ,FILESPF,LUNSPF
     &  ,FILEINT,LUNINT
     &  ,FILEHB,LUNHB
     &  ,FILEWB,LUNWB
     &  ,FILEZZPYYP,LUNZZPYYP
     &  ,FILEWBT,LUNWBT
     &  ,FILEABS,LUNABS,FILEFF,LUNEFF
     &  ,FILEMG,LUNMG
     &  ,FILEFL0,FILEFLF
     &  ,LUNFL0,LUNFLF
     &  ,FILETBZ,LUNTBZ,filetbx
     &  ,LUNSTO,FILESTO
     &  ,LUNSTOF,FILESTOF,FILESTOE,FILESTOEF
     &  ,LUNRAY,FILERAY
     &  ,LUNAM,FILEAM
     &  ,LUNAMO,FILEAMO
     &  ,LUNS,FILES
     &  ,LUNSE,FILESE
     &  ,LUNSF,FILESF
     &  ,LUNSEF,FILESEF
     &  ,LUNC,FILEC
     &  ,LUNCE,FILECE
     &  ,LUNCF,FILECF
     &  ,LUNCEF,FILECEF
     &  ,FILEBRILL,FILEBRILLE,FILEBRILLF,FILEBRILLEF
     &  ,LUNREC,FILEREC
     &  ,LUNBMAP,FILEBMAP
     &  ,LUN3DCOE,LUN3DFIT
     &  ,FILE3DCOE,FILE3DFIT
     &  ,LUN2DHFIT,FILE2DHFIT
     &  ,LUNPHFIT,FILEPHFIT
     &  ,LUNPH,FILEPH,LUNGENL,LUNGENI,FILEGENL,FILEGENI
     &  ,LUNAMPLI,FILEAMPLI,LUNFT,FILEFTH,FILEFTV
C5.10.95     &                 B,RB,

      NAMELIST/MYFILES/FILEB0,LUNB0,DYB0,DZB0,NYB0,NZB0,NXB0,
     &  FILET0,LUNT0,FILEL0,LUNL0,
     &  FILEL,LUNL,FILEA,LUNA,FILEP,LUNP,
     &  FILEO,LUNO,FILED,LUND,
     &  FILECOD,LUNCOD,
     &  FILEH,LUNH,
     &  FILEF,LUNF,
     &  FILETB,LUNTB
     &  ,FILEJ,LUNJ
     &  ,FILETR,LUNTR,FILEBE,LUNBE
     &  ,FILEOB,LUNOB
     &  ,FILEFR,LUNFR
     &  ,FILESP0,LUNSP0
     &  ,FILEPOW,LUNPOW
     &  ,FILEINT,LUNINT
     &  ,FILEHB,LUNHB
     &  ,FILEWB,LUNWB
     &  ,FILEZZPYYP,LUNZZPYYP
     &  ,FILESPF,LUNSPF
     &  ,FILEWBT,LUNWBT
     &  ,FILEABS,LUNABS,FILEFF,LUNEFF
     &  ,FILEMG,LUNMG
     &  ,FILEFL0,FILEFLF
     &  ,LUNFL0,LUNFLF
     &  ,FILETBZ,LUNTBZ,filetbx
     &  ,LUNSTO,FILESTO
     &  ,LUNSTOF,FILESTOF,FILESTOE,FILESTOEF
     &  ,LUNRAY,FILERAY
     &  ,LUNAM,FILEAM
     &  ,LUNAMO,FILEAMO
     &  ,LUNS,FILES
     &  ,LUNSE,FILESE
     &  ,LUNSF,FILESF
     &  ,LUNSEF,FILESEF
     &  ,LUNC,FILEC
     &  ,LUNCE,FILECE
     &  ,LUNCF,FILECF
     &  ,LUNCEF,FILECEF
     &  ,FILEBRILL,FILEBRILLE,FILEBRILLF,FILEBRILLEF
     &  ,LUNREC,FILEREC
     &  ,LUNBMAP,FILEBMAP
     &  ,LUN3DCOE,LUN3DFIT
     &  ,FILE3DCOE,FILE3DFIT
     &  ,LUN2DHFIT,FILE2DHFIT
     &  ,LUNPHFIT,FILEPHFIT
     &  ,LUNPH,FILEPH,LUNGENL,LUNGENI,FILEGENL,FILEGENI
     &  ,LUNAMPLI,FILEAMPLI,LUNFT,FILEFTH,FILEFTV
*KEEP,TRACK.
      INTEGER NCO,MCO,IBYONLY,ITRACK

      DOUBLE PRECISION PHIX,PHIMX,PHIMN
     &  ,XMX,XMN,YMX,YMN,ZMX,ZMN
     &  ,BXMX,BXMN,BYMX,BYMN,BZMX,BZMN
     &  ,XMXAE,XMNAE,YMXAE,YMNAE,ZMXAE,ZMNAE
     &  ,BXMXAE,BXMNAE,BYMXAE,BYMNAE,BZMXAE,BZMNAE
     &  ,BINT0,PINT,tint
     &  ,BINT1X,BINT1Y,BINT1Z,BINT2X,BINT2Y,BINT2Z,BINT3Y,BINT3YA
     &  ,DTIM0,DS0
     &  ,B2INTY
     &  ,WTRA2I,TTRA2I,HTRA2I,WTRA2IC,
     &  XTRACK,YTRACK,ZTRACK,
     &  VXTRACK,VYTRACK,VZTRACK

      COMMON/MINMAXC/
     &  PHIX,PHIMX,PHIMN,XMX,XMN,YMX,YMN,ZMX,ZMN
     &  ,BXMX,BXMN,BYMX,BYMN,BZMX,BZMN
     &  ,XMXAE,XMNAE,YMXAE,YMNAE,ZMXAE,ZMNAE
     &  ,BXMXAE,BXMNAE,BYMXAE,BYMNAE,BZMXAE,BZMNAE
     &  ,BINT0,PINT,tint
     &  ,BINT1X,BINT1Y,BINT1Z,BINT2X,BINT2Y,BINT2Z,BINT3Y,BINT3YA
     &  ,DTIM0,DS0
     &  ,WTRA2I,TTRA2I,HTRA2I,WTRA2IC
     &  ,B2INTY
     &  ,XTRACK,YTRACK,ZTRACK
     &  ,VXTRACK,VYTRACK,VZTRACK
     &  ,NCO,MCO,IBYONLY,ITRACK
*KEEP,OPTIC.
      INTEGER ISNORDER,NZOPT,NZPOPT,NYOPT,NYPOPT,I2DIM
     &       ,IPHASPAC,IHPHSPAC

      DOUBLE PRECISION
     &        DZOPT,DZPOPT,DYOPT,DYPOPT,
     &        DLAPER,ZAPERT,YAPERT,
     &        DRANDO,DSCALE,XLTRAN
     &       ,OPSTARTX,OPENDX,OPSTARTY,OPENDY,OPSTARTZ,OPENDZ
     &       ,OPNX,OPNY,OPNZ,OPNFX,OPNFY,OPNFZ
     &       ,BETA0ZH,BETA0YH,BETA0ZL,BETA0YL

      COMMON/OPTIC/
     &        DZOPT,DZPOPT,DYOPT,DYPOPT,
     &        DLAPER,ZAPERT,YAPERT,
     &        DRANDO,DSCALE,XLTRAN
     &       ,OPSTARTX,OPENDX,OPSTARTY,OPENDY,OPSTARTZ,OPENDZ
     &       ,OPNX,OPNY,OPNZ,OPNFX,OPNFY,OPNFZ
     &       ,BETA0ZH,BETA0YH,BETA0ZL,BETA0YL
     &       ,ISNORDER,NZOPT,NZPOPT,NYOPT,NYPOPT,I2DIM
     &       ,IPHASPAC,IHPHSPAC

      NAMELIST/OPTIK/NZOPT,DZOPT,NYOPT,DYOPT,
     &        NZPOPT,DZPOPT,NYPOPT,DYPOPT,
     &        DLAPER,ZAPERT,YAPERT
     &       ,OPSTARTX,OPSTARTY,OPSTARTZ,OPENDX,OPENDY,OPENDZ
     &       ,OPNX,OPNY,OPNZ,OPNFX,OPNFY,OPNFZ
     &       ,DRANDO,DSCALE,XLTRAN,ISNORDER,I2DIM
     &       ,BETA0ZH,BETA0YH,BETA0ZL,BETA0YL
     &       ,IPHASPAC,IHPHSPAC
*KEEP,SOURCEF90.

      INTEGER NBADDP,NROIP
      PARAMETER (NBADDP=100,NROIP=512)
      INTEGER NROI,NROIA,NIDSOURCE,NSOURCE,NDWSOU,NLPOIO,
     &          ISOURO,NSADD,NBUFF,NDSPAR,IROIASYEXP(NROIP)

      DOUBLE PRECISION ROIX(NROIP),ROIP(NROIP)

      COMMON/SOURCEC/ROIX,ROIP
     &,NROI,NROIA,NIDSOURCE,NSOURCE,NDWSOU,NLPOIO,ISOURO,NSADD,NBUFF,NDSPAR
     &,IROIASYEXP

      NAMELIST /ROIN/ NROI,ROIX,ROIP,IROIASYEXP
*KEEP,FREQS.
      CHARACTER(65) ABSCOM,EFFCOM

      INTEGER NFREQ,NINTFREQ,IFILTER,IFILMUL,IEFFI,IHFIL
     &         ,NFREQEP,NFREQEM
     &         ,NFREQ0,NFREQ0M,NFREQ0P

C260194 {
      DOUBLE PRECISION WELLEN(NDFREQP),WELLENC,WELLENCF
C260194 }

      DOUBLE PRECISION FREQ(NDFREQP),ABSMU(NDFREQP),ABSMUTOT(NDFREQP),
     &  FREQLOW,FREQHIG,ABSTHI,ABSDEN
      DOUBLE PRECISION EXPMU(NDFREQP),FREQC,FREQCF,SPECCUT
     &        ,ABSMUEN(NDFREQP),AREAM2,FRSCALE,EFF(NDFREQP)

      COMMON/FREQSC/
     &         WELLEN,WELLENC,WELLENCF
     &        ,FREQ,ABSMU,ABSMUTOT,FREQLOW,FREQHIG,ABSTHI,ABSDEN
     &        ,EXPMU,FREQC,FREQCF,SPECCUT
     &        ,ABSMUEN,AREAM2,FRSCALE,EFF
     &        ,NFREQ,NINTFREQ,IFILTER,IFILMUL,IEFFI,IHFIL
     &        ,NFREQEP,NFREQEM
     &        ,NFREQ0,NFREQ0M,NFREQ0P
     &        ,ABSCOM,EFFCOM

      NAMELIST/FREQN/FREQLOW,FREQHIG,NINTFREQ,ABSTHI,AREAM2
     &               ,IHFIL,IFILTER,IFILMUL,IEFFI,FREQC,FREQCF,SPECCUT,FRSCALE
*KEEP,OBSERVF90.

      DOUBLE PRECISION PINCEN(3),PINW,PINH,pinr,pinrad,
     &  OBSVDZ,OBSVDY,OBS1X,OBS1Y,OBS1Z,OBSVDR,OBSVDPHI
     &  ,pinhsc,pinwsc,rpinsph

      INTEGER NOBSV,NOBSVZ,NOBSVY,MPINZ,MPINY,MPINR,MPINPHI
     &  ,mpinyorig,mpinzorig
      INTEGER MOBSV,MOBSVZ,MOBSVY,MEDGEZ,MEDGEY
      INTEGER MMEDGEZ,MMEDGEY,IRFILOB,MEDGER
     &  ,IPBRILL,ICBRILL
     &  ,NOBSVRPHI,NOBSVR,NOBSVPHI
     &  ,MOBSVRPHI,MOBSVR,MOBSVPHI,IQUADPHI

      COMMON/OBSERV/OBSVDZ,OBSVDY,OBS1X,OBS1Y,OBS1Z
     &  ,PINCEN,PINW,PINH,pinr,pinrad,OBSVDR,OBSVDPHI
     &  ,pinhsc,pinwsc
     &  ,rpinsph
     &  ,NOBSV,NOBSVZ,NOBSVY,MPINZ,MPINY,MPINR,MPINPHI
     &  ,mpinyorig,mpinzorig
     &  ,MOBSV,MOBSVZ,MOBSVY,MEDGEZ,MEDGEY
     &  ,MMEDGEZ,MMEDGEY,IRFILOB,MEDGER
     &  ,NOBSVRPHI,NOBSVR,NOBSVPHI
     &  ,MOBSVRPHI,MOBSVR,MOBSVPHI
     &  ,IPBRILL,ICBRILL,IQUADPHI

      NAMELIST/PINHOLE/PINCEN,MPINZ,MPINY,MPINR,MPINPHI,OBSVDR,OBSVDPHI,
     &  PINW,PINH,pinr,pinrad,MEDGEZ,MEDGEY
     &  ,MMEDGEZ,MMEDGEY,IRFILOB,OBS1X,OBS1Y,OBS1Z,OBSVDZ,OBSVDY
     &  ,IPBRILL,IQUADPHI
     &  ,pinhsc,pinwsc
     &  ,rpinsph
*KEEP,SPECT.

      INTEGER NPWALL,NPOLMX

      COMPLEX*16 VPOLA(3),VSTOKES(4,3)
      COMPLEX*16 REFLEC(3)

      DOUBLE PRECISION SPECNOR,POWNOR

      DOUBLE PRECISION SPECPOWVHT

      DOUBLE PRECISION PINDOS
      DOUBLE PRECISION WFLUXTI,WFLUXTIF,SPECTOTMX(6),WALL(2)
     &  ,POWBCUT,XWALLI,XWALLE
     &  ,POWCOR,XABSORB,ZABSORB(2)

      REAL*4 TOTGAM(6),TOTMAX(12)

      REAL*4  STOKCMX(4,2),G3CMX(2)
     &  ,STOKCMXF(4,2),G3CMXF(2)
     &  ,STOKCMXE(4,2),G3CMXE(2)
     &  ,STOKCMXEF(4,2),G3CMXEF(2)
     &  ,BRILLCMX(12,2),B3CMX(2)
     &  ,BRILLCMXF(12,2),B3CMXF(2)
     &  ,BRILLCMXE(12,2),B3CMXE(2)
     &  ,BRILLCMXEF(12,2),B3CMXEF(2)
     &  ,WSTOKMX(4,2),WG3MX(2)
     &  ,WSTOKMXF(4,2),WG3MXF(2)
     &  ,WSTOKMXE(4,2),WG3MXE(2)
     &  ,WSTOKMXEF(4,2),WG3MXEF(2)
     &  ,STOKESMAX(4,4),STOKESMAXF(4,4)
     &  ,STOKESMAXE(4,4),STOKESMAXEF(4,4)

      COMMON/SPECTC/
     &   VPOLA,VSTOKES,REFLEC
     &  ,SPECNOR,POWNOR
     &  ,SPECPOWVHT
     &  ,PINDOS
     &  ,WFLUXTI
     &  ,WFLUXTIF,SPECTOTMX
     &  ,WALL,POWBCUT,XWALLI,XWALLE
     &  ,POWCOR,XABSORB,ZABSORB
     &  ,TOTGAM,TOTMAX
     &  ,STOKCMX,G3CMX
     &  ,STOKCMXF,G3CMXF
     &  ,STOKCMXE,G3CMXE
     &  ,STOKCMXEF,G3CMXEF
     &  ,BRILLCMX,B3CMX
     &  ,BRILLCMXF,B3CMXF
     &  ,BRILLCMXE,B3CMXE
     &  ,BRILLCMXEF,B3CMXEF
     &  ,WSTOKMX,WG3MX
     &  ,WSTOKMXF,WG3MXF
     &  ,WSTOKMXE,WG3MXE
     &  ,WSTOKMXEF,WG3MXEF
     &  ,STOKESMAX,STOKESMAXF
     &  ,STOKESMAXE,STOKESMAXEF
     &  ,NPWALL,NPOLMX


      NAMELIST/SPECTN/
     &        VPOLA,REFLEC
     &        ,WALL,POWBCUT,XWALLI,XWALLE,NPWALL,POWCOR,XABSORB
     &        ,ZABSORB,NPOLMX
*KEEP,SPECDIP.

      INTEGER NDIPP
      PARAMETER (NDIPP=501) !Check LIDIMP

      DOUBLE PRECISION B0DIP(NDIPP),ECDIP(NDIPP),RHODIP(NDIPP)
     &  ,X0DIP(NDIPP),Y0DIP(NDIPP),Z0DIP(NDIPP)
     &  ,BXDIP(NDIPP),BYDIP(NDIPP),BZDIP(NDIPP)
     &  ,VXDIP(NDIPP),VYDIP(NDIPP),VZDIP(NDIPP),
     &  APERTHICK,APERHANG,APERVANG

      INTEGER NDIP

      COMMON/SPECDIPC/B0DIP,ECDIP,RHODIP
     &  ,X0DIP,Y0DIP,Z0DIP
     &  ,BXDIP,BYDIP,BZDIP
     &  ,VXDIP,VYDIP,VZDIP,
     &  APERTHICK,APERHANG,APERVANG,
     &  NDIP

      NAMELIST/SPECDIPN/NDIP,X0DIP,Y0DIP,Z0DIP
     &  ,BXDIP,BYDIP,BZDIP
     &  ,VXDIP,VYDIP,VZDIP,
     &  APERTHICK,APERHANG,APERVANG
*KEEP,COLLI.
      INTEGER IBL0CUT,ISOUREXT

      DOUBLE PRECISION CX1,CY1,CZ1,CX2,CY2,CZ2,WID1,HIG1,WID2,HIG2
     &  ,WBL0CUT,WGWINFC,WBL0HYS
     &  ,APERX,APERY,APERZ,APERHIG,APERWID

      COMMON/COLLIC/ CX1,CY1,CZ1,CX2,CY2,CZ2,WID1,HIG1,WID2,HIG2
     &  ,WBL0CUT,WGWINFC,WBL0HYS
     &  ,APERX,APERY,APERZ,APERHIG,APERWID,IBL0CUT,ISOUREXT

      NAMELIST/COLLIN/ CX1,CY1,CZ1,CX2,CY2,CZ2,WID1,HIG1,WID2,HIG2
     &  ,WBL0CUT,WGWINFC,WBL0HYS
     &  ,APERX,APERY,APERZ,APERHIG,APERWID,IBL0CUT,ISOUREXT
*KEEP,WFOLDF90.
C      INTEGER max

      INTEGER NGFOURZ,NGFOURY,ISIGSTO
     &         ,NSIGE

      DOUBLE PRECISION GCOEFH(NGCOEFP,LIDIMP),GCOEFV(NGCOEFP,LIDIMP)
      DOUBLE PRECISION XKGAUSS(NGCOEFP,LIDIMP),YKGAUSS(NGCOEFP,LIDIMP)

      DOUBLE PRECISION WSIG2Z(max(10,LIDIMP)),WSIG2Y(max(10,LIDIMP))
      DOUBLE PRECISION DSIG2Z(max(10,LIDIMP)),DSIG2Y(max(10,LIDIMP))
     &        ,WSIGZ(max(10,LIDIMP)),WSIGY(max(10,LIDIMP))
     &        ,BSIGZ(max(10,LIDIMP)),BSIGY(max(10,LIDIMP))
     &        ,SIGRC,SIGRPC
     &        ,BSIGZP(max(10,LIDIMP)),BSIGYP(max(10,LIDIMP))
     &        ,DSIGZ(max(10,LIDIMP)),DSIGY(max(10,LIDIMP))
     &        ,DGSIGZ(max(10,LIDIMP)),DGSIGY(max(10,LIDIMP))

      DOUBLE PRECISION ESPREAD


      COMMON/WFOLDC/
     &         GCOEFH,GCOEFV
     &        ,XKGAUSS,YKGAUSS
     &        ,WSIG2Z,WSIG2Y
     &        ,DSIG2Z,DSIG2Y
     &        ,WSIGZ,WSIGY
     &        ,BSIGZ,BSIGY
     &        ,SIGRC,SIGRPC
     &        ,BSIGZP,BSIGYP
     &        ,DSIGZ,DSIGY
     &        ,DGSIGZ,DGSIGY
     &        ,ESPREAD
     &        ,NGFOURZ,NGFOURY,ISIGSTO
     &        ,NSIGE


      NAMELIST/WFOLDN/BSIGZ,BSIGY,BSIGZP,BSIGYP
     &        ,WSIGZ,WSIGY,DGSIGZ,DGSIGY,NGFOURZ,NGFOURY,ISIGSTO
     &        ,SIGRC,SIGRPC
     &        ,ESPREAD,NSIGE

*KEEP,WUSEM.
	INTEGER
     &	IFLUSS,ICONV

	COMMON/WUSEMC/IFLUSS,ICONV
*KEEP,AMPLI.

      INTEGER IAMPDIMP
      PARAMETER (IAMPDIMP=10000)

      INTEGER IMAMPLI,IAMPSKIP,IAMPTERM,IAMPREAD,modeph
     &  ,IAMPOBSV,IAMPCOMP,IAMPREP,IAMPSUP,IAMPSEED,iamppin,iamppincirc
     &  ,iampcoh,iampincoh,nampbunchharm,noemitph,noespreadph,mampthreads

      DOUBLE PRECISION AMPFREQ,ampr2corr,AMPPHI(IAMPDIMP),AMPSHIFT(IAMPDIMP)
     &  ,AMPSCALE(IAMPDIMP),AMPRAN,FACAMPLI,phrERROR,
     &  phrshift,phrb0h,phrb0v,phrperl,phdx,phdy,phdz,phrxbeta,
     &  phrbetah,phralphah,phrbetav,phralphav,phrespread,phremith,phremitv,
     &  ampcohsig,ampbunchlen,ampbunchcharge,ampbunchp0,ampbunchr56,
     &  phrdisph,phrdispph,phrdispv,phrdisppv,phrbunlen

      COMMON/AMPLIC/
     &  ampfreq,ampr2corr,AMPPHI,AMPSHIFT,AMPSCALE,AMPRAN,FACAMPLI,phrERROR
     &  ,ampcohsig,ampbunchlen,ampbunchcharge,ampbunchp0,ampbunchr56,phrxbeta,
     &  phrshift,phrb0h,phrb0v,phrperl,phdx,phdy,phdz,
     &  phrbetah,phralphah,phrbetav,phralphav,phrespread,phremith,phremitv,
     &  phrdisph,phrdispph,phrdispv,phrdisppv,phrbunlen,
     &  IMAMPLI,IAMPSKIP,IAMPTERM,IAMPREAD,modeph
     &  ,IAMPOBSV,IAMPCOMP,IAMPREP,IAMPSUP,IAMPSEED,iamppin,iamppincirc
     &  ,iampcoh,iampincoh,nampbunchharm,noemitph,noespreadph,mampthreads

      NAMELIST/AMPLIN/
     &  IMAMPLI,IAMPSKIP,IAMPTERM,IAMPREAD
     & ,IAMPCOMP,IAMPREP
     & ,AMPSHIFT,AMPSCALE,ampfreq,ampr2corr,AMPPHI,IAMPSUP,AMPRAN,IAMPSEED
     &  ,ampcohsig,ampbunchlen,ampbunchcharge,ampbunchp0,ampbunchr56
     &  ,iampcoh,iampincoh,nampbunchharm

      NAMELIST/PHASEREPN/phrERROR,noemitph,noespreadph,modeph,phrxbeta,
     &  phrshift,phrperl,phrb0h,phrb0v,phdx,phdy,phdz,
     &  phrdisph,phrdispph,phrdispv,phrdisppv,phrbunlen,
     &  phrbetah,phralphah,phrbetav,phralphav,phrespread,phremith,phremitv
*KEEP,USERVAR.
*
*     USER NAMELIST
*
      DOUBLE PRECISION UDUM

      DOUBLE PRECISION USER(1000)
      DOUBLE PRECISION ULOOP(1000)

      INTEGER IUDUM
      CHARACTER(128) CUDUM
      CHARACTER(128) userchar(1000)

      COMMON/USERC/USER,ULOOP,UDUM,IUDUM,CUDUM,userchar

      NAMELIST/USERN/USER,UDUM,IUDUM,CUDUM,userchar
*KEEP,PHYCON.
      DOUBLE PRECISION
     &  CLIGHT1,CGAM1,CQ1,alpha1,
     &  dnull1,done1,sqrttwopi1,
     &  EMASSG1,EMASSE1,ECHARGE1,EMASSKG1,EPS01,ERAD1,
     &  GRARAD1,
     &  HBAR1,HBAREV1,HPLANCK1,
     &  PI1,POL1CON1,POL2CON1,
     &  RADGRA1,rmu01,rmu04pi1,
     &  TWOPI1,HALFPI1,
     &  WTOE1,gaussn1,cK934,powcon1,ecdipev1,ecdipkev1

      COMMON/PHYCON1/
     &  CLIGHT1,CGAM1,CQ1,alpha1,
     &  dnull1,done1,sqrttwopi1,
     &  EMASSG1,EMASSE1,ECHARGE1,EMASSKG1,EPS01,ERAD1,
     &  GRARAD1,
     &  HBAR1,HBAREV1,HPLANCK1,
     &  PI1,POL1CON1,POL2CON1,
     &  RADGRA1,rmu01,rmu04pi1,
     &  TWOPI1,HALFPI1,
     &  WTOE1,gaussn1,cK934,powcon1,ecdipev1,ecdipkev1
*KEEP,WHBOOK.
      INTEGER NMAXHISP
      PARAMETER (NMAXHISP=1000)

      integer, parameter :: mhbookp=100

      INTEGER
     &  IDSPEC,IDSPECF
     &  ,IDSPECH,IDSPECV
     &  ,IDSPECFH,IDSPECFV
     &  ,IDFOLFNZ,IDFOLFNY
     &  ,IDTRACKZ,IDTRACKY,IDBX,IDBY,IDBZ,IDBETAH
     &  ,IDTRCKSZ,IDTRCKSY,IDSBX,IDSBY,IDSBZ
     &  ,IDBETAV,IDBETAPH,IDBETAPV,IDETA,IDFREQ,IDCODE
     &  ,IDINPUT,IDOUTP
     &  ,IDHS,IDHX,IDHSR3,IDHXR3,IDFREQF
     &  ,IDBETHPC,IDBETHP,IDBPHPC,IDBPHP,IDPOWER
     &  ,IDSTOKES0,IDSTOKES1,IDSTOKES2,IDSTOKES3
     &  ,IDSTOKFS0,IDSTOKFS1,IDSTOKFS2,IDSTOKFS3
     &  ,NIDFREQ,NIDFREQP,NIDSPEC,NIDSPECRPHI,NIDPOW
     &  ,NIDSPECF,NIDSTOK,NIDSTOKF,NIDSTOKE,NIDSTOKEF
     &  ,NIDFIL
     &  ,NIDMUEN
     &  ,NIDTRAC
     &  ,NIDBPOLY
     &  ,NIDTRACK,NIDMINI,NIDTRCKG,NIDPHANA
     &  ,IDPHASE

      INTEGER
     &  IDFRS0,IDFRS1,IDFRS2,IDFRS3
     &  ,IDFRP,IDFRP2,IDFRP3,IDFRP23,IDFRG3,IDFRG23
     &  ,IDFRS0E,IDFRS1E,IDFRS2E,IDFRS3E
     &  ,IDFRPE,IDFRP2E,IDFRP3E,IDFRP23E,IDFRG3E,IDFRG23E
     &  ,IDFRS0F,IDFRS1F,IDFRS2F,IDFRS3F
     &  ,IDFRPF,IDFRP2F,IDFRP3F,IDFRP23F,IDFRG3F,IDFRG23F
     &  ,IDFRS0EF,IDFRS1EF,IDFRS2EF,IDFRS3EF
     &  ,IDFRPEF,IDFRP2EF,IDFRP3EF,IDFRP23EF,IDFRG3EF,IDFRG23EF

      INTEGER
     &  ICFREQ,ICFREQF
     &  ,ICFRS0,ICFRS1,ICFRS2,ICFRS3
     &  ,ICFRP,ICFRP2,ICFRP3,ICFRP23,ICFRG3,ICFRG23
     &  ,ICFRS0E,ICFRS1E,ICFRS2E,ICFRS3E
     &  ,ICFRPE,ICFRP2E,ICFRP3E,ICFRP23E,ICFRG3E,ICFRG23E
     &  ,ICFRS0F,ICFRS1F,ICFRS2F,ICFRS3F
     &  ,ICFRPF,ICFRP2F,ICFRP3F,ICFRP23F,ICFRG3F,ICFRG23F
     &  ,ICFRS0EF,ICFRS1EF,ICFRS2EF,ICFRS3EF
     &  ,ICFRPEF,ICFRP2EF,ICFRP3EF,ICFRP23EF,ICFRG3EF,ICFRG23EF
     &  ,ICFRB0,ICFRB1,ICFRB2,ICFRB3
     &  ,ICFRB0F,ICFRB1F,ICFRB2F,ICFRB3F
     &  ,ICFRB0E,ICFRB1E,ICFRB2E,ICFRB3E
     &  ,ICFRB0EF,ICFRB1EF,ICFRB2EF,ICFRB3EF,
     &  ICFRP1EF,ICFRP1E,ICFRP1F,ICFRP1,IDFRP1EF,IDFRP1E,IDFRP1F,IDFRP1

      INTEGER IDAX,IDAY,IDAZ

      REAL*4 VMX
      INTEGER IQUEST
      COMMON/QUEST/IQUEST(100)

      COMMON/PAWVMX/VMX
     &  ,IDSPEC,IDSPECF
     &  ,IDSPECH,IDSPECV
     &  ,IDSPECFH,IDSPECFV
     &  ,IDFOLFNZ,IDFOLFNY
     &  ,IDTRACKZ,IDTRACKY,IDBX,IDBY,IDBZ,IDBETAH
     &  ,IDTRCKSZ,IDTRCKSY,IDSBX,IDSBY,IDSBZ
     &  ,IDBETAV,IDBETAPH,IDBETAPV,IDETA,IDFREQ,IDCODE
     &  ,IDINPUT,IDOUTP
     &  ,IDHS,IDHX,IDHSR3,IDHXR3
     &  ,IDBETHPC,IDBETHP,IDBPHPC,IDBPHP,IDPOWER
     &  ,IDSTOKES0,IDSTOKES1,IDSTOKES2,IDSTOKES3
     &  ,IDSTOKFS0,IDSTOKFS1,IDSTOKFS2,IDSTOKFS3
     &  ,NIDFREQ,NIDFREQP,NIDFIL,NIDSPEC,NIDSPECRPHI,NIDPOW
     &  ,NIDSPECF,NIDSTOK,NIDSTOKF,NIDSTOKE,NIDSTOKEF
     &  ,NIDTRAC
     &  ,NIDTRACK,NIDMINI,NIDTRCKG,NIDPHANA
     &  ,NIDBPOLY
     &  ,NIDMUEN,IDFREQF
     &  ,IDFRS0,IDFRS1,IDFRS2,IDFRS3
     &  ,IDFRP,IDFRP2,IDFRP3,IDFRP23,IDFRG3,IDFRG23
     &  ,IDFRS0E,IDFRS1E,IDFRS2E,IDFRS3E
     &  ,IDFRPE,IDFRP2E,IDFRP3E,IDFRP23E,IDFRG3E,IDFRG23E
     &  ,IDFRS0F,IDFRS1F,IDFRS2F,IDFRS3F
     &  ,IDFRPF,IDFRP2F,IDFRP3F,IDFRP23F,IDFRG3F,IDFRG23F
     &  ,IDFRS0EF,IDFRS1EF,IDFRS2EF,IDFRS3EF
     &  ,IDFRPEF,IDFRP2EF,IDFRP3EF,IDFRP23EF,IDFRG3EF,IDFRG23EF
     &  ,ICFREQ,ICFREQF
     &  ,ICFRS0,ICFRS1,ICFRS2,ICFRS3
     &  ,ICFRP,ICFRP2,ICFRP3,ICFRP23,ICFRG3,ICFRG23
     &  ,ICFRS0E,ICFRS1E,ICFRS2E,ICFRS3E
     &  ,ICFRPE,ICFRP2E,ICFRP3E,ICFRP23E,ICFRG3E,ICFRG23E
     &  ,ICFRS0F,ICFRS1F,ICFRS2F,ICFRS3F
     &  ,ICFRPF,ICFRP2F,ICFRP3F,ICFRP23F,ICFRG3F,ICFRG23F
     &  ,ICFRS0EF,ICFRS1EF,ICFRS2EF,ICFRS3EF
     &  ,ICFRPEF,ICFRP2EF,ICFRP3EF,ICFRP23EF,ICFRG3EF,ICFRG23EF
     &  ,ICFRB0,ICFRB1,ICFRB2,ICFRB3
     &  ,ICFRB0F,ICFRB1F,ICFRB2F,ICFRB3F
     &  ,ICFRB0E,ICFRB1E,ICFRB2E,ICFRB3E
     &  ,ICFRB0EF,ICFRB1EF,ICFRB2EF,ICFRB3EF
     &  ,IDAX,IDAY,IDAZ
     &  ,IDPHASE,
     &  ICFRP1EF,ICFRP1E,ICFRP1F,ICFRP1,IDFRP1EF,IDFRP1E,IDFRP1F,IDFRP1
*KEEP,pawcmn.
*KEEP,PHASEF90.

      INTEGER
     &  nphasez,nphasey,mphasez,mphasey,NIDPHASE
     &  ,NIDGEO,IDSEL,IHSEL,NPHELEMP,NPHELEM,iphfold
     &  ,iwigner,nwigthetaz,nwigthetay
     &  ,nwigefold,nosplinewef,iwigefold

      PARAMETER (NPHELEMP=5)

      DOUBLE PRECISION
     &  phgshift,PHCENX,PHCENY,PHCENZ,PHWID,PHHIG,
     &  PHAPERZM,PHAPERZP,PHAPERZPM,PHAPERZPP,
     &  PHAPERYM,PHAPERYP,PHAPERYPM,PHAPERYPP,
     &  PHGEOSUM(NDFREQP),PHGEOSEL(NDFREQP),PHBEAM(NDFREQP),
     &  PHELEM(5,4,NPHELEMP),
     &  PHBETH,PHBETV
     &  ,wigthetaz,wigthetay,wigthetazcen,wigthetaycen

      COMMON/PHASEC/
     &  phgshift,PHCENX,PHCENY,PHCENZ,PHWID,PHHIG,
     &  PHAPERZM,PHAPERZP,PHAPERZPM,PHAPERZPP,
     &  PHAPERYM,PHAPERYP,PHAPERYPM,PHAPERYPP,
     &  PHGEOSUM,PHGEOSEL,PHELEM,PHBEAM,
     &  PHBETH,PHBETV,
     &  wigthetaz,wigthetay,wigthetazcen,wigthetaycen,
     &  iwigefold,
     &  nphasez,nphasey,mphasez,mphasey,NIDPHASE,NIDGEO,IDSEL,IHSEL,NPHELEM,iphfold
     &  ,iwigner,nwigthetaz,nwigthetay,nwigefold,nosplinewef

      NAMELIST/PHASEN/
     &  phgshift,PHCENX,PHCENY,PHCENZ,PHWID,PHHIG,
     &  PHAPERZM,PHAPERZP,PHAPERZPM,PHAPERZPP,
     &  PHAPERYM,PHAPERYP,PHAPERYPM,PHAPERYPP,
     &  PHBETH,PHBETV,
     &  nphasez,nphasey,mphasez,mphasey,IHSEL,NPHELEM,PHELEM,iphfold
     &  ,iwigner,nwigthetaz,nwigthetay
     &  ,wigthetaz,wigthetay,wigthetazcen,wigthetaycen,nwigefold,nosplinewef

*KEEP,ntuple2.
      integer ntupip,nid222,ntupusp,nid223
      parameter (ntupip=61,ntupusp=10)
      double precision fillp(ntupip),fillu(ntupusp)

      common/tupipc/nid222,nid223,fillp,fillu
*KEEP,genpho.
      double precision GENPHOPHSH
      integer NGENPHOEFOLD,NOSPLINEEF,NELECGENPHO,NPHO,MODERAN,NORANONE,KGENDONE
      common/genphoc/ GENPHOPHSH,NGENPHOEFOLD,NOSPLINEEF,NELECGENPHO,NPHO,MODERAN,NORANONE,KGENDONE
      namelist/genphon/GENPHOPHSH,NGENPHOEFOLD,NOSPLINEEF,NELECGENPHO,NPHO,MODERAN,NORANONE
*KEEP,datetime.
      integer *8 i_util_date_time
      real util_time
      integer idatetime(8), i_util_date, i_util_time
      character(10) dtday,dttime,dtzone
      character(14) ch_i_util_date_time
      common/datec/idatetime,i_util_date,i_util_time,
     &  i_util_date_time,dtday,dttime,dtzone,
     &  ch_i_util_date_time
*KEEP,wvers.
      character(55) chwversion
      real wversion
      common/wvers/wversion,chwversion
*KEND.

      INTEGER ICYCLE,ISCRATCH

      INTEGER I
      integer :: iline=0
      BYTE I1(96)

      CHARACTER(32) LINE_1,LINE_2,LINE_3
      CHARACTER(1) LINE32_1(32),LINE32_2(32),LINE32_3(32)
      CHARACTER(96) C96,EMPTY
      CHARACTER(1) C1(96)

      EQUIVALENCE(I1,C1,C96)
      EQUIVALENCE(LINE_1,LINE32_1)
      EQUIVALENCE(LINE_2,LINE32_2)
      EQUIVALENCE(LINE_3,LINE32_3)

      COMMON/CLINEc/LINE_1,LINE_2,LINE_3

      integer jday,jtim,ius

      DATA EMPTY/' '/

      fillp=-9999.

      call date_and_time(dtday,dttime,dtzone,idatetime)
      read(dtday(3:8),*)jday
      read(dttime(1:6),*)jtim

      fillp(1)=dmyenergy
      fillp(2)=dmycur
      if (ispec.ne.0) then
        fillp(3)=ipin
        fillp(4)=ipincirc
        fillp(5)=pincen(1)
        fillp(6)=pincen(2)
        fillp(7)=pincen(3)
        fillp(8)=pinw
        fillp(9)=pinh
        fillp(10)=pinr
        if (ipin.eq.3) then
          fillp(11)=mpinzorig
          fillp(12)=mpinyorig
        else
          fillp(11)=mpinz
          fillp(12)=mpiny
        endif
        fillp(13)=mpinr
        fillp(14)=mpinphi
        fillp(15)=icbrill
        fillp(16)=obsv(1,icbrill)
        fillp(17)=obsv(2,icbrill)
        fillp(18)=obsv(3,icbrill)
      endif
      fillp(19)=phcenx
      fillp(20)=bsigz(1)
      fillp(21)=bsigy(1)
      fillp(22)=bsigzp(1)
      fillp(23)=bsigyp(1)
      fillp(24)=espread
      if (ispec.ne.0) then
        fillp(25)=ifreq2p
        fillp(26)=nintfreq
        fillp(27)=freqlow
        fillp(28)=freqhig
      endif
      fillp(29)=ispec
      if (ispec.ne.0) then
        fillp(30)=ispecmode
        fillp(31)=ispecdip
        fillp(32)=nlpoi
        fillp(33)=banwid
      endif
      fillp(34)=ibunch
      fillp(35)=nbunch
      fillp(36)=neinbunch
      if (ispec.ne.0) then
        fillp(37)=iampli
      endif
      fillp(38)=ieneloss
      fillp(39)=ifold
      fillp(40)=iefold
      fillp(41)=icode
      fillp(42)=jday
      fillp(43)=jtim
      fillp(44)=wversion
      fillp(45)=istokes
      fillp(46)=nobsvy
      fillp(47)=nobsvz
      fillp(48)=wall(1)
      fillp(49)=wall(2)
      fillp(50)=xabsorb
      fillp(51)=zabsorb(1)
      fillp(52)=zabsorb(2)
      if (ispec.ne.0) then
        fillp(53)=ibrill
      endif
      fillp(54)=ihbeta
      fillp(55)=kampli
      if (ispec.ne.0) then
        fillp(56)=iphase
        fillp(57)=iwigner
        fillp(58)=nwigefold
        fillp(59)=NELECGENPHO
        fillp(60)=NGENPHOEFOLD
        fillp(61)=MODERAN
      endif

      call hfm(nid222,fillp)

      do ius=1,ntupusp
        fillu(ius)=user(ius)
      enddo

      call hfm(nid223,fillu)

      CALL MHROUT(0,ICYCLE,' ')

      if (iroottrees.lt.0) return

      IF (IHOUTP.NE.0) THEN

        CALL hbntm(IDOUTP,'OUTPUT FILE WAVE.OUT',' ')
        CALL hbnamcm(IDOUTP,'LINE',LINE_1
     &    ,'LINE_1:C*32,LINE_2:C*32,LINE_3:C*32')

        REWIND(LUNGFO)

100     C96=EMPTY
        READ (LUNGFO,'(A96)',END=90) C96

C- FILL CWN BUFFER

        DO I=1,32
          LINE32_1(I)=C1(I)
          LINE32_2(I)=C1(I+32)
          LINE32_3(I)=C1(I+64)
        ENDDO

        CALL hfntm(IDOUTP)
        iline=iline+1
        GOTO 100

90      CONTINUE


        DO ISCRATCH=1,ICYCLE-1
          CALL HSCRm(IDOUTP,ISCRATCH,' ')
        ENDDO

        CALL hdeletnomh(IDOUTP)

        rewind(lungfo)

        write(luns_mh(kfile_mh),'(a)')" ! ------------------------------------------------"
        write(luns_mh(kfile_mh),'(a)')"                   16                    4    ! id and kind of histogram of Ntuple"
        write(luns_mh(kfile_mh),'(a)')"          20     ! length of title"
        write(luns_mh(kfile_mh),'(a)')"OUTPUT FILE WAVE.OUT"
        write(luns_mh(kfile_mh),'(a)')"                    6           3          11    "
     &    //"! length of pathname, number of variables, and length of variable names"
        write(luns_mh(kfile_mh),'(a)')"//WAVE"
        write(luns_mh(kfile_mh),'(a)')"LINE_1:C*32"
        write(luns_mh(kfile_mh),'(a)')"LINE_2:C*32"
        write(luns_mh(kfile_mh),'(a)')"LINE_3:C*32"
        write(luns_mh(kfile_mh),*)iline," ! number of entries"

        do i=1,iline
          read (lungfo,'(a96)') c96
          write(luns_mh(kfile_mh),'(a)')c96
        enddo

        close(lungfo)

        open(unit=lungfo,file=filegfo,status='old',access='append')

      ENDIF !IHOUTP

      IF (IHINDEX.NE.0) then
        open(unit=99,file='wave_index.his')
        CALL HOUTPUm(99)
        CALL HLDIRm(' ','IT')
        close(99)
        call houtpum(6)
c obsolete          call system('mv fort.99 wave_index.his')
        print*,' '
        print*,'      Index of histograms written to wave_index.his'
        print*,' '
      endif

      if (iroottrees.ge.0) then
        CALL hrendm('WAVE')
      endif

      CLOSE(LUNHB)

        call mh_end

      RETURN
      END
