*CMZ :  4.00/15 27/04/2022  08.30.53  by  Michael Scheer
*CMZ :  3.06/00 15/02/2019  17.36.39  by  Michael Scheer
*CMZ :  3.03/02 04/03/2016  18.30.51  by  Michael Scheer
*CMZ :  3.00/01 26/03/2013  20.22.51  by  Michael Scheer
*CMZ :  2.42/00 06/09/2002  14.55.56  by  Michael Scheer
*CMZ :  2.41/13 03/09/2002  13.42.24  by  Michael Scheer
*CMZ :  2.41/11 20/08/2002  17.46.17  by  Michael Scheer
*CMZ :  2.16/04 20/06/2000  17.41.11  by  Michael Scheer
*CMZ :  2.16/00 24/05/2000  18.51.59  by  Michael Scheer
*CMZ :  2.15/00 19/05/2000  10.49.29  by  Michael Scheer
*CMZ :  2.14/02 25/04/2000  17.26.31  by  Michael Scheer
*CMZ :  2.14/00 18/04/2000  17.48.40  by  Michael Scheer
*-- Author : Michael Scheer
      SUBROUTINE REC_HELI(IUREC,GRARAD,ISIDE,ISHIFT,JSHIFT)
*KEEP,gplhint.
!******************************************************************************
!
!      Copyright 2013 Helmholtz-Zentrum Berlin (HZB)
!      Hahn-Meitner-Platz 1
!      D-14109 Berlin
!      Germany
!
!      Author Michael Scheer, Michael.Scheer@Helmholtz-Berlin.de
!
! -----------------------------------------------------------------------
!
!    This program is free software: you can redistribute it and/or modify
!    it under the terms of the GNU General Public License as published by
!    the Free Software Foundation, either version 3 of the License, or
!    (at your option) any later version.
!
!    This program is distributed in the hope that it will be useful,
!    but WITHOUT ANY WARRANTY; without even the implied warranty of
!    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!    GNU General Public License for more details.
!
!    You should have received a copy (wave_gpl.txt) of the GNU General Public
!    License along with this program.
!    If not, see <http://www.gnu.org/licenses/>.
!
!    Dieses Programm ist Freie Software: Sie koennen es unter den Bedingungen
!    der GNU General Public License, wie von der Free Software Foundation,
!    Version 3 der Lizenz oder (nach Ihrer Option) jeder spaeteren
!    veroeffentlichten Version, weiterverbreiten und/oder modifizieren.
!
!    Dieses Programm wird in der Hoffnung, dass es nuetzlich sein wird, aber
!    OHNE JEDE GEWAEHRLEISTUNG, bereitgestellt; sogar ohne die implizite
!    Gewaehrleistung der MARKTFAEHIGKEIT oder EIGNUNG FueR EINEN BESTIMMTEN ZWECK.
!    Siehe die GNU General Public License fuer weitere Details.
!
!    Sie sollten eine Kopie (wave_gpl.txt) der GNU General Public License
!    zusammen mit diesem Programm erhalten haben. Wenn nicht,
!    siehe <http://www.gnu.org/licenses/>.
!
!******************************************************************************
*KEND.

      IMPLICIT NONE

*KEEP,cmpara.
      include 'cmpara.cmn'
*KEEP,klotz.
      include 'klotz.cmn'
*KEND.

      DOUBLE PRECISION RECEND,TOTLEN,TOTLEN2,GRARAD,DX1,BCS(NKLOTZ)

      REAL XRAN(NKLOTZ),YRAN(NKLOTZ),rr(2)
      INTEGER IPER,IUREC,ISIDE,JSHIFT,ISHIFT,I,N,IMAGTOTO,IMAGTOTS

      IMAGTOTS=IMAGTOT

      TOTLEN=(2+KRECPER(IUREC))*4.D0*URECLX(IUREC)
      TOTLEN2=TOTLEN/2.D0
      RECEND=URECCX(IUREC)-TOTLEN2

      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF

      XLEN(IMAGTOT)=URECLX(IUREC)/2.D0
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=270.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*ISHIFT
      DX1=DX(IMAGTOT)
      DY(IMAGTOT)=URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC))
      DZ(IMAGTOT)=(URECCZ(IUREC)-(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      BC(IMAGTOT)=-URECBC(IUREC)/4.D0
      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF
      XLEN(IMAGTOT)=URECLX(IUREC)/2.D0
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=90.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*JSHIFT
      DY(IMAGTOT)=-(URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC)))
      DZ(IMAGTOT)=(URECCZ(IUREC)+(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      DX(IMAGTOT)=DX(IMAGTOT)+URSHADD(IUREC)
      BC(IMAGTOT)=-URECBC(IUREC)/4.D0
      RECEND=RECEND+XLEN(IMAGTOT)

      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF
      XLEN(IMAGTOT)=URECLX(IUREC)
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=0.D0
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*ISHIFT
      DY(IMAGTOT)=URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC))
      DZ(IMAGTOT)=(URECCZ(IUREC)-(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      BC(IMAGTOT)=-URECBC(IUREC)/4.D0
      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF
      XLEN(IMAGTOT)=URECLX(IUREC)
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=0.D0
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*JSHIFT
      DY(IMAGTOT)=-(URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC)))
      DZ(IMAGTOT)=(URECCZ(IUREC)+(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      DX(IMAGTOT)=DX(IMAGTOT)+URSHADD(IUREC)
      BC(IMAGTOT)=-URECBC(IUREC)/4.D0
      RECEND=RECEND+XLEN(IMAGTOT)

      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF
      XLEN(IMAGTOT)=URECLX(IUREC)/2.D0
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=90.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*ISHIFT
      DY(IMAGTOT)=URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC))
      DZ(IMAGTOT)=(URECCZ(IUREC)-(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      BC(IMAGTOT)=-URECBC(IUREC)/4.D0
      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF
      XLEN(IMAGTOT)=URECLX(IUREC)/2.D0
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=270.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*JSHIFT
      DY(IMAGTOT)=-(URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC)))
      DZ(IMAGTOT)=(URECCZ(IUREC)+(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      DX(IMAGTOT)=DX(IMAGTOT)+URSHADD(IUREC)
      BC(IMAGTOT)=-URECBC(IUREC)/4.D0
      RECEND=RECEND+XLEN(IMAGTOT)

      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF
      XLEN(IMAGTOT)=URECLX(IUREC)/2.D0
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=90.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*ISHIFT
      DY(IMAGTOT)=URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC))
      DZ(IMAGTOT)=(URECCZ(IUREC)-(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      BC(IMAGTOT)=-URECBC(IUREC)*0.75D0
      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF
      XLEN(IMAGTOT)=URECLX(IUREC)/2.D0
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=270.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*JSHIFT
      DY(IMAGTOT)=-(URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC)))
      DZ(IMAGTOT)=(URECCZ(IUREC)+(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      DX(IMAGTOT)=DX(IMAGTOT)+URSHADD(IUREC)
      BC(IMAGTOT)=-URECBC(IUREC)*0.75D0
      RECEND=RECEND+XLEN(IMAGTOT)

      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF
      XLEN(IMAGTOT)=URECLX(IUREC)
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=180.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*ISHIFT
      DY(IMAGTOT)=URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC))
      DZ(IMAGTOT)=(URECCZ(IUREC)-(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      BC(IMAGTOT)=-URECBC(IUREC)*0.75D0
      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF
      XLEN(IMAGTOT)=URECLX(IUREC)
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=180.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*JSHIFT
      DY(IMAGTOT)=-(URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC)))
      DZ(IMAGTOT)=(URECCZ(IUREC)+(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      DX(IMAGTOT)=DX(IMAGTOT)+URSHADD(IUREC)
      BC(IMAGTOT)=-URECBC(IUREC)*0.75D0
      RECEND=RECEND+XLEN(IMAGTOT)

      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF
      XLEN(IMAGTOT)=URECLX(IUREC)/2.D0
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=270.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*ISHIFT
      DY(IMAGTOT)=URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC))
      DZ(IMAGTOT)=(URECCZ(IUREC)-(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      BC(IMAGTOT)=-URECBC(IUREC)*0.75D0
      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF
      XLEN(IMAGTOT)=URECLX(IUREC)/2.D0
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=90.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*JSHIFT
      DY(IMAGTOT)=-(URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC)))
      DZ(IMAGTOT)=(URECCZ(IUREC)+(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      DX(IMAGTOT)=DX(IMAGTOT)+URSHADD(IUREC)
      BC(IMAGTOT)=-URECBC(IUREC)*0.75D0
      RECEND=RECEND+XLEN(IMAGTOT)

      IMAGTOTO=IMAGTOT
      DO IPER=1,KRECPER(IUREC)

          IMAGTOT=IMAGTOT+1
            IF(IMAGTOT.GT.NKLOTZ) THEN
                WRITE(6,*)
                WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
                WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
                WRITE(6,*)
                STOP
            ENDIF
      XLEN(IMAGTOT)=URECLX(IUREC)/2.D0
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=90.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*ISHIFT
      DY(IMAGTOT)=URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC))
      DZ(IMAGTOT)=(URECCZ(IUREC)-(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      BC(IMAGTOT)=URECBC(IUREC)

      dmupar(IMAGTOT)=URECmupar(IUREC)
      dmuper(IMAGTOT)=URECmuper(IUREC)

      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF

      XLEN(IMAGTOT)=URECLX(IUREC)/2.D0
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=270.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*JSHIFT
      DY(IMAGTOT)=-(URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC)))
      DZ(IMAGTOT)=(URECCZ(IUREC)+(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      DX(IMAGTOT)=DX(IMAGTOT)+URSHADD(IUREC)
      BC(IMAGTOT)=URECBC(IUREC)
      dmupar(IMAGTOT)=URECmupar(IUREC)
      dmuper(IMAGTOT)=URECmuper(IUREC)
      RECEND=RECEND+XLEN(IMAGTOT)

        IMAGTOT=IMAGTOT+1
        IF(IMAGTOT.GT.NKLOTZ) THEN
          WRITE(6,*)
          WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
          WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
          WRITE(6,*)
          STOP
        ENDIF

      XLEN(IMAGTOT)=URECLX(IUREC)
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=180.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*ISHIFT
      DY(IMAGTOT)=URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC))
      DZ(IMAGTOT)=(URECCZ(IUREC)-(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      BC(IMAGTOT)=URECBC(IUREC)

      dmupar(IMAGTOT)=URECmupar(IUREC)
      dmuper(IMAGTOT)=URECmuper(IUREC)

      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF

      XLEN(IMAGTOT)=URECLX(IUREC)
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=180.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*JSHIFT
      DY(IMAGTOT)=-(URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC)))
      DZ(IMAGTOT)=(URECCZ(IUREC)+(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      DX(IMAGTOT)=DX(IMAGTOT)+URSHADD(IUREC)
      BC(IMAGTOT)=URECBC(IUREC)
      dmupar(IMAGTOT)=URECmupar(IUREC)
      dmuper(IMAGTOT)=URECmuper(IUREC)
      RECEND=RECEND+XLEN(IMAGTOT)

        IMAGTOT=IMAGTOT+1
        IF(IMAGTOT.GT.NKLOTZ) THEN
          WRITE(6,*)
          WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
          WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
          WRITE(6,*)
          STOP
        ENDIF

        XLEN(IMAGTOT)=URECLX(IUREC)/2.D0
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=270.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*ISHIFT
      DY(IMAGTOT)=URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC))
      DZ(IMAGTOT)=(URECCZ(IUREC)-(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      BC(IMAGTOT)=URECBC(IUREC)
      dmupar(IMAGTOT)=URECmupar(IUREC)
      dmuper(IMAGTOT)=URECmuper(IUREC)

        IMAGTOT=IMAGTOT+1
        IF(IMAGTOT.GT.NKLOTZ) THEN
          WRITE(6,*)
          WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
          WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
          WRITE(6,*)
          STOP
        ENDIF

        XLEN(IMAGTOT)=URECLX(IUREC)/2.D0
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=90.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*JSHIFT
      DY(IMAGTOT)=-(URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC)))
      DZ(IMAGTOT)=(URECCZ(IUREC)+(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      DX(IMAGTOT)=DX(IMAGTOT)+URSHADD(IUREC)
      BC(IMAGTOT)=URECBC(IUREC)

      dmupar(IMAGTOT)=URECmupar(IUREC)
      dmuper(IMAGTOT)=URECmuper(IUREC)

      RECEND=RECEND+XLEN(IMAGTOT)

      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF

      XLEN(IMAGTOT)=URECLX(IUREC)/2.D0
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=270.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*ISHIFT
      DY(IMAGTOT)=URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC))
      DZ(IMAGTOT)=(URECCZ(IUREC)-(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      BC(IMAGTOT)=URECBC(IUREC)

      dmupar(IMAGTOT)=URECmupar(IUREC)
      dmuper(IMAGTOT)=URECmuper(IUREC)

      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF

      XLEN(IMAGTOT)=URECLX(IUREC)/2.D0
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=90.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*JSHIFT
      DY(IMAGTOT)=-(URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC)))
      DZ(IMAGTOT)=(URECCZ(IUREC)+(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      DX(IMAGTOT)=DX(IMAGTOT)+URSHADD(IUREC)
      BC(IMAGTOT)=URECBC(IUREC)

      dmupar(IMAGTOT)=URECmupar(IUREC)
      dmuper(IMAGTOT)=URECmuper(IUREC)

      RECEND=RECEND+XLEN(IMAGTOT)

      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF

      XLEN(IMAGTOT)=URECLX(IUREC)
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=0.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*ISHIFT
      DY(IMAGTOT)=URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC))
      DZ(IMAGTOT)=(URECCZ(IUREC)-(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      BC(IMAGTOT)=URECBC(IUREC)
      dmupar(IMAGTOT)=URECmupar(IUREC)
      dmuper(IMAGTOT)=URECmuper(IUREC)

        IMAGTOT=IMAGTOT+1
        IF(IMAGTOT.GT.NKLOTZ) THEN
          WRITE(6,*)
          WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
          WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
          WRITE(6,*)
          STOP
        ENDIF

        XLEN(IMAGTOT)=URECLX(IUREC)
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=0.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*JSHIFT
      DY(IMAGTOT)=-(URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC)))
      DZ(IMAGTOT)=(URECCZ(IUREC)+(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      DX(IMAGTOT)=DX(IMAGTOT)+URSHADD(IUREC)
      BC(IMAGTOT)=URECBC(IUREC)
      dmupar(IMAGTOT)=URECmupar(IUREC)
      dmuper(IMAGTOT)=URECmuper(IUREC)
      RECEND=RECEND+XLEN(IMAGTOT)

        IMAGTOT=IMAGTOT+1
        IF(IMAGTOT.GT.NKLOTZ) THEN
          WRITE(6,*)
          WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
          WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
          WRITE(6,*)
          STOP
        ENDIF

        XLEN(IMAGTOT)=URECLX(IUREC)/2.D0
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=90.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*ISHIFT
      DY(IMAGTOT)=URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC))
      DZ(IMAGTOT)=(URECCZ(IUREC)-(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      BC(IMAGTOT)=URECBC(IUREC)
        dmupar(IMAGTOT)=URECmupar(IUREC)
        dmuper(IMAGTOT)=URECmuper(IUREC)

        IMAGTOT=IMAGTOT+1
        IF(IMAGTOT.GT.NKLOTZ) THEN
          WRITE(6,*)
          WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
          WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
          WRITE(6,*)
          STOP
        ENDIF

        XLEN(IMAGTOT)=URECLX(IUREC)/2.D0
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=270.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*JSHIFT
      DY(IMAGTOT)=-(URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC)))
      DZ(IMAGTOT)=(URECCZ(IUREC)+(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      DX(IMAGTOT)=DX(IMAGTOT)+URSHADD(IUREC)
      BC(IMAGTOT)=URECBC(IUREC)

      dmupar(IMAGTOT)=URECmupar(IUREC)
      dmuper(IMAGTOT)=URECmuper(IUREC)

      RECEND=RECEND+XLEN(IMAGTOT)

      ENDDO !KRECPER

      IF (NURANMOD.EQ.1) THEN
        CALL RNORML(XRAN,NKLOTZ,rr)
        DO I=1,NKLOTZ
1         IF (ABS(XRAN(I)).GT.BCRANSIG) THEN
            CALL RNORML(XRAN(I),1,rr)
            GOTO 1
          ENDIF
        ENDDO
        IF (BCRAN.GE.0.D0) THEN
          DO I=1,NKLOTZ
            YRAN(I)=XRAN(I)*BCRAN
          ENDDO
        ELSE
          DO I=1,NKLOTZ
            YRAN(I)=-BCRAN
          ENDDO
        ENDIF
        DO I=IMAGTOTO+1,IMAGTOTO+6
          XRAN(I)=YRAN(I+6)/2.
          YRAN(I)=0.D0
        ENDDO  !IMAG
        DO I=IMAGTOT-5,IMAGTOT
          YRAN(I)=0.D0
        ENDDO  !IMAG
        DO I=IMAGTOTO+7,IMAGTOT-6
          XRAN(I)=YRAN(I)+YRAN(I-6)/2.+YRAN(I+6)/2. ! "+" due to angles
        ENDDO  !IMAG
        DO I=IMAGTOT-5,IMAGTOT
          XRAN(I)=YRAN(I-6)/2.
        ENDDO  !IMAG
        DO I=IMAGTOTO+1,IMAGTOT
          IF (DX(I)-XLEN(I)/2.D0.GE.BCSTART
     &        .AND.DX(I)+XLEN(I)/2.D0.LE.BCEND) THEN
            BC(I)=BC(I)*(1.+XRAN(I))
          ENDIF
        ENDDO  !IMAG
      ELSE IF (NURANMOD.EQ.2) THEN
        CALL RNORML(XRAN,NKLOTZ,rr)
        DO I=1,NKLOTZ
11        IF (ABS(XRAN(I)).GT.BCRANSIG) THEN
            CALL RNORML(XRAN(I),1,rr)
            GOTO 11
          ENDIF
        ENDDO
        IF (BCRAN.GE.0.D0) THEN
          DO I=1,NKLOTZ
            YRAN(I)=XRAN(I)*BCRAN
          ENDDO
        ELSE
          DO I=1,NKLOTZ
            YRAN(I)=-BCRAN
          ENDDO
        ENDIF
        DO I=IMAGTOT-5,IMAGTOT
          YRAN(I)=0.D0
        ENDDO  !IMAG
        DO I=IMAGTOTO+1,IMAGTOT-6
          XRAN(I)=YRAN(I)+YRAN(I+6) ! "+" due to angles
        ENDDO  !IMAG
        DO I=IMAGTOT-5,IMAGTOT
          XRAN(I)=YRAN(I-6)
        ENDDO  !IMAG
        DO I=IMAGTOTO+1,IMAGTOT
          IF (DX(I)-XLEN(I)/2.D0.GE.BCSTART
     &        .AND.DX(I)+XLEN(I)/2.D0.LE.BCEND) THEN
            BC(I)=BC(I)*(1.+XRAN(I))
          ENDIF
        ENDDO  !IMAG
      ENDIF !(NRANMOD.EQ.1)

      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF
      XLEN(IMAGTOT)=URECLX(IUREC)/2.D0
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=90.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*ISHIFT
      DY(IMAGTOT)=URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC))
      DZ(IMAGTOT)=(URECCZ(IUREC)-(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      BC(IMAGTOT)=URECBC(IUREC)*0.75D0

      dmupar(IMAGTOT)=URECmupar(IUREC)
      dmuper(IMAGTOT)=URECmuper(IUREC)

      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF
      XLEN(IMAGTOT)=URECLX(IUREC)/2.D0
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=270.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*JSHIFT
      DY(IMAGTOT)=-(URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC)))
      DZ(IMAGTOT)=(URECCZ(IUREC)+(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      DX(IMAGTOT)=DX(IMAGTOT)+URSHADD(IUREC)
      BC(IMAGTOT)=URECBC(IUREC)*0.75D0

      dmupar(IMAGTOT)=URECmupar(IUREC)
      dmuper(IMAGTOT)=URECmuper(IUREC)

      RECEND=RECEND+XLEN(IMAGTOT)

      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF

      XLEN(IMAGTOT)=URECLX(IUREC)
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=180.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*ISHIFT
      DY(IMAGTOT)=URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC))
      DZ(IMAGTOT)=(URECCZ(IUREC)-(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      BC(IMAGTOT)=URECBC(IUREC)*0.75D0

      dmupar(IMAGTOT)=URECmupar(IUREC)
      dmuper(IMAGTOT)=URECmuper(IUREC)

      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF
      XLEN(IMAGTOT)=URECLX(IUREC)
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=180.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*JSHIFT
      DY(IMAGTOT)=-(URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC)))
      DZ(IMAGTOT)=(URECCZ(IUREC)+(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      DX(IMAGTOT)=DX(IMAGTOT)+URSHADD(IUREC)
      BC(IMAGTOT)=URECBC(IUREC)*0.75D0

      dmupar(IMAGTOT)=URECmupar(IUREC)
      dmuper(IMAGTOT)=URECmuper(IUREC)

      RECEND=RECEND+XLEN(IMAGTOT)

      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF
      XLEN(IMAGTOT)=URECLX(IUREC)/2.D0
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=270.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*ISHIFT
      DY(IMAGTOT)=URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC))
      DZ(IMAGTOT)=(URECCZ(IUREC)-(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      BC(IMAGTOT)=URECBC(IUREC)*0.75D0

      dmupar(IMAGTOT)=URECmupar(IUREC)
      dmuper(IMAGTOT)=URECmuper(IUREC)

      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF
      XLEN(IMAGTOT)=URECLX(IUREC)/2.D0
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=90.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*JSHIFT
      DY(IMAGTOT)=-(URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC)))
      DZ(IMAGTOT)=(URECCZ(IUREC)+(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      DX(IMAGTOT)=DX(IMAGTOT)+URSHADD(IUREC)
      BC(IMAGTOT)=URECBC(IUREC)*0.75D0

      dmupar(IMAGTOT)=URECmupar(IUREC)
      dmuper(IMAGTOT)=URECmuper(IUREC)

      RECEND=RECEND+XLEN(IMAGTOT)

      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF
      XLEN(IMAGTOT)=URECLX(IUREC)/2.D0
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=270.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*ISHIFT
      DY(IMAGTOT)=URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC))
      DZ(IMAGTOT)=(URECCZ(IUREC)-(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      BC(IMAGTOT)=URECBC(IUREC)/4.D0

      dmupar(IMAGTOT)=URECmupar(IUREC)
      dmuper(IMAGTOT)=URECmuper(IUREC)

      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF
      XLEN(IMAGTOT)=URECLX(IUREC)/2.D0
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=90.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*JSHIFT
      DY(IMAGTOT)=-(URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC)))
      DZ(IMAGTOT)=(URECCZ(IUREC)+(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      DX(IMAGTOT)=DX(IMAGTOT)+URSHADD(IUREC)
      BC(IMAGTOT)=URECBC(IUREC)/4.D0

      dmupar(IMAGTOT)=URECmupar(IUREC)
      dmuper(IMAGTOT)=URECmuper(IUREC)

      RECEND=RECEND+XLEN(IMAGTOT)

      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF
      XLEN(IMAGTOT)=URECLX(IUREC)
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=0.D0
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*ISHIFT
      DY(IMAGTOT)=URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC))
      DZ(IMAGTOT)=(URECCZ(IUREC)-(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      BC(IMAGTOT)=URECBC(IUREC)/4.D0

      dmupar(IMAGTOT)=URECmupar(IUREC)
      dmuper(IMAGTOT)=URECmuper(IUREC)

      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF
      XLEN(IMAGTOT)=URECLX(IUREC)
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=0.D0
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*JSHIFT
      DY(IMAGTOT)=-(URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC)))
      DZ(IMAGTOT)=(URECCZ(IUREC)+(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      DX(IMAGTOT)=DX(IMAGTOT)+URSHADD(IUREC)
      BC(IMAGTOT)=URECBC(IUREC)/4.D0

      dmupar(IMAGTOT)=URECmupar(IUREC)
      dmuper(IMAGTOT)=URECmuper(IUREC)

      RECEND=RECEND+XLEN(IMAGTOT)

      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF
      XLEN(IMAGTOT)=URECLX(IUREC)/2.D0
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=90.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*ISHIFT
      DY(IMAGTOT)=URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC))
      DZ(IMAGTOT)=(URECCZ(IUREC)-(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      BC(IMAGTOT)=URECBC(IUREC)/4.D0

      dmupar(IMAGTOT)=URECmupar(IUREC)
      dmuper(IMAGTOT)=URECmuper(IUREC)

      IMAGTOT=IMAGTOT+1
      IF(IMAGTOT.GT.NKLOTZ) THEN
        WRITE(6,*)
        WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
        WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
        WRITE(6,*)
        STOP
      ENDIF
      XLEN(IMAGTOT)=URECLX(IUREC)/2.D0
      YLEN(IMAGTOT)=URECLY(IUREC)
      ZLEN(IMAGTOT)=URECLZ(IUREC)
      THETA(IMAGTOT)=270.D0*GRARAD
      PHI(IMAGTOT)=0.D0
      DX(IMAGTOT)=RECEND+XLEN(IMAGTOT)/2.D0+URSHIFT(IUREC)*JSHIFT
      DY(IMAGTOT)=-(URECLY(IUREC)/2.D0+(URECGAP(IUREC)+(DX(IMAGTOT)-DX1)*UTAPER(IUREC)))
      DZ(IMAGTOT)=(URECCZ(IUREC)+(URECLZ(IUREC)+URSPLIT(IUREC))/2.D0)*ISIDE
      DX(IMAGTOT)=DX(IMAGTOT)+URSHADD(IUREC)
      BC(IMAGTOT)=URECBC(IUREC)/4.D0

      dmupar(IMAGTOT)=URECmupar(IUREC)
      dmuper(IMAGTOT)=URECmuper(IUREC)

      RECEND=RECEND+XLEN(IMAGTOT)

      IF (BCRAN.NE.0.D0) THEN

C--- NURANMOD.EQ.3.OR.NURANMOD.EQ.4

        IF (NURANMOD.EQ.3.OR.NURANMOD.EQ.4) THEN

          N=0
          DO I=IMAGTOTS+1,IMAGTOT,2
            N=N+1
            BCS(N)=BC(I)
          ENDDO

          CALL REC_UBCERROR(N,BCS,NURANMOD,BCRAN,BCRANSIG)

          N=0
          DO I=IMAGTOTS+1,IMAGTOT,2
            N=N+1
            BC(I)=BCS(N)
          ENDDO

          N=0
          DO I=IMAGTOTS+2,IMAGTOT,2
            N=N+1
            BCS(N)=BC(I)
          ENDDO

          CALL REC_UBCERROR(N,BCS,NURANMOD,BCRAN,BCRANSIG)

          N=0
          DO I=IMAGTOTS+2,IMAGTOT,2
            N=N+1
            BC(I)=BCS(N)
          ENDDO

        ENDIF  !(NURANMOD.EQ.3.OR.NURANMOD.EQ.4)
      ENDIF !(BCRAN.NE.0.D0)

      IF (UBANGERR(IUREC).NE.0) THEN

C--- NURANMOD.EQ.3.OR.NURANMOD.EQ.4

      IF (NURANMOD.EQ.3.OR.NURANMOD.EQ.4) THEN

            IF(IMAGTOTS+2*(IMAGTOT-IMAGTOTS).GT.NKLOTZ) THEN
                WRITE(6,*)
                WRITE(6,*)'*** ERROR IN REC_HELI: DIMENSION EXCEEDED ***'
                WRITE(6,*)'INCREASE PARAMETER NKLOTZ IN FILE KLOTZ.CMN'
                WRITE(6,*)
                STOP
            ENDIF

          N=IMAGTOT
          DO I=IMAGTOTS+1,IMAGTOT
         N=N+1
                XLEN(N)=XLEN(I)
                YLEN(N)=YLEN(I)
                ZLEN(N)=ZLEN(I)
                DX(N)=DX(I)
                DY(N)=DY(I)
                DZ(N)=DZ(I)
                THETA(N)=90.D0*GRARAD
                PHI(N)=90.D0*GRARAD
                BC(N)=BC(I)
          ENDDO

          N=IMAGTOT-IMAGTOTS
          IMAGTOTS=IMAGTOTS+N
          IMAGTOT=IMAGTOTS+N

          N=0
          DO I=IMAGTOTS+1,IMAGTOT,2
         N=N+1
                BCS(N)=BC(I)
          ENDDO

            CALL REC_UBANGERROR(N,BCS,NURANMOD,UBANGERR(IUREC),
     &        ubansig(iurec),USIGOFFY(IUREC))

          N=0
          DO I=IMAGTOTS+1,IMAGTOT,2
         N=N+1
                BC(I)=BCS(N)
          ENDDO

          N=0
          DO I=IMAGTOTS+2,IMAGTOT,2
         N=N+1
                BCS(N)=BC(I)
          ENDDO

            CALL REC_UBANGERROR(N,BCS,NURANMOD,UBANGERR(IUREC),
     &        ubansig(iurec),USIGOFFY(IUREC))

          N=0
          DO I=IMAGTOTS+2,IMAGTOT,2
         N=N+1
                BC(I)=BCS(N)
          ENDDO

      ENDIF !(NURANMOD.EQ.3.OR.NURANMOD.EQ.4)
      ENDIF !(BCRAN.NE.0.D0)

      RETURN
      END
