*CMZ :  4.01/04 17/10/2023  12.50.02  by  Michael Scheer
*CMZ :  4.01/03 15/05/2023  14.11.27  by  Michael Scheer
*CMZ :  4.00/17 15/11/2022  10.13.07  by  Michael Scheer
*CMZ :  4.00/15 01/06/2022  16.47.26  by  Michael Scheer
*CMZ :  4.00/11 28/06/2021  10.33.06  by  Michael Scheer
*-- Author : Michael Scheer
      subroutine uout

*KEEP,TRACKF90U.
      USE TRACKF90
*KEEP,SPECTF90U.
      USE SPECTF90

*KEND.

      use sourcef90
      use observf90
      use afreqf90
      !use waveenv

      implicit none

*KEEP,CONTRL.
      DOUBLE PRECISION ECPHOTON,XSTART,XINTER,XSTOP,XIANF,XIEND,GWINFC,BL0CUT,BL0HYS
     &  ,DMYGAMMA,DMYBETA,VXIN,VYIN,DMYCUR,BANWID,D1MBETA
     &  ,VZIN,YSTART,ZSTART,DEVLEN,DEVLEN2,DMYENERGY,GMOM,EMOM
     &  ,XSTARTH,XSTOPH,DBRHO,BMOVECUT
     &  ,BXSTART,BYSTART,BZSTART,AXSTART,AYSTART,AZSTART
     &  ,BXSTOP,BYSTOP,BZSTOP,AXSTOP,AYSTOP,AZSTOP,XBSYM

      INTEGER       LIDIM,NBDIM,NOMDIM,IBFDIM4,IBFDIM2,IANZPL,LUNGFI,
     &  LUNGFO,IWFILSP0,IWFILSPF,IWFILPOW,
     &  NXPAN,NYPAN,
     &  ICODE,KOUT,KBFELD,KHALBA,KHALBASY,KUNDUGAP,KBEXTERN,KBAMWLS,
     &  IRFILF,IBGAUSS,KCIRC,
     &  KSIGN,ICHECK,KBETAX,IFORM0,IFORM,
     &  IWFILB0,IRFILB0,IWFILF,IWSECTMAGS,IRFILP,IRFILB,ITRAKT,
     &  IWFILT0,IRFILT0,IWFILL0,IRFILL0,
     &  IEXPL0,NLPOI,IWFILL,IWFILA,IRFILA,ISAVLO,
     &  IOPTIC,IGENFUN,IDISPER,IEMIT,IERZANA,IEMIAHW,
     &  IBHARD,IERZFUN,IRANDO,IBHTRACK,IBHELM,KBGENESIS,ISPLINE,
     &  IBSYM,IWLSOPT,IKBFORM,IRBTAB,NBTAB,IJUST,MYINUM,NSTEPMX,
     &  ICTEST ,IHFOLD,IBSYMY,IBSYMZ,
     &  NWMAX,ISPEC,IVELOFIELD,NDFREQ,NDOBSV,IFREQ2P,IWFILINT,JWFILINT,
     &  IHPIN,
     &  NDPAWC,IPIN,IPOLA,ifold,ibunch,ISPECANA,NGCOEF,ISPECMODE,
     &  NDMASHZ,NDMASHY,NDOBSVZ,NDOBSVY,ISIGUSR,ISPECINT,
     &  IPINALL,IHBOOK,IHINDEX,
     &  IHTRACK,IHTRSMP,IHTRACKM,IHBETA,IUNIT,IUNITS,IF1DIM,IHFREQ,
     &  IPOWER,NDPOL,IBEAMPOL,KUCROSS,KMAGSEQ,IMGSQF,KMAGCOR,
     &  IWBTAB,IABEND,irbmap6,iwbmap,
     &  IWFILFL0,IWFILFLF,IRPHI,
     &  IUSEM,IPINCIRC,ISTOKES,irbtabzy,ifourbtabzy,IRBTABXYZ,ISPECANAF,IBRILL,
     &  IWFILSTO,IWFLSTOF,IWFLSTOE,IWFLSTOEF,IRFILSP0,IRFILSTO,ISPECSUM,
     &  IWFILS,IWFILSF,IWFILSE,IWFILSEF,
     &  IWFILB,IWFILBF,IWFILBE,IWFILBEF,
     &  IWFILBRILL,IWFILBRILLF,IWFILBRILLE,IWFILBRILLEF,
     &  KELLIP,IWFILRAY,KELLANA,
     &  IPHASE,IDOSE,IPHOTON,IEFOLD,IDESYNC,ISPECDIP,
     &  IUOUT,IUNAME,IUSTEP,IPHASEANA,
     &  KBPOLYH,IGFLOAT
     &  ,KBPOLY3D,IWBPOLY3D
     &  ,KBPOLY2DH,IWBPOLY2DH
     &  ,KBPharm,IWBpharm
     &  ,KBREC,KBPOLYMAG,IBATCH,kbundumag,kbundumap,kbunduverb
     &  ,IMAGSPLN,IHINPUT,IHOUTP,IMHBCOM,IMAGJOB
     &  ,IW_BLEN,IW_BLENF,IW_CIRC
     &  ,IHLIMIT_C,IHISINI_C,ihisascii,iroottrees,IBFORCE
     &  ,iampli,kampli,IAMPJIT,IUNDULATOR,IWIGGLER,IEXPERT,IBSUPER,IBERROR
     &  ,ieneloss,iefield,iroothdf5,nocern,iadjust,iwarnbmap,iwarnmyb,mthreads

      CHARACTER(65) CODE
      CHARACTER     CHISASCII

      COMMON/CONTRL/ECPHOTON,
     &  XSTART,XINTER,XSTOP,XIANF,XIEND,GWINFC,BL0CUT,BL0HYS
     &  ,DMYGAMMA,DMYBETA,VXIN,VYIN,DMYCUR,BANWID,D1MBETA
     &  ,VZIN,YSTART,ZSTART,DEVLEN,DEVLEN2,DMYENERGY,GMOM,EMOM
     &  ,XSTARTH,XSTOPH,DBRHO,BMOVECUT
     &  ,BXSTART,BYSTART,BZSTART,AXSTART,AYSTART,AZSTART
     &  ,BXSTOP,BYSTOP,BZSTOP,AXSTOP,AYSTOP,AZSTOP,XBSYM
     &  ,LIDIM,NBDIM,NOMDIM,IBFDIM4,IBFDIM2,IANZPL,LUNGFI,
     &  LUNGFO,IWFILSP0,IWFILSPF,IWFILPOW,
     &  NXPAN,NYPAN,
     &  ICODE,KOUT,KBFELD,KHALBA,KHALBASY,KUNDUGAP,KBEXTERN,KBAMWLS,
     &  IRFILF,IBGAUSS,KCIRC,
     &  KSIGN,ICHECK,KBETAX,IFORM0,IFORM,
     &  IWFILB0,IRFILB0,IWFILF,IWSECTMAGS,IRFILP,IRFILB,ITRAKT,
     &  IWFILT0,IRFILT0,IWFILL0,IRFILL0,
     &  IEXPL0,NLPOI,IWFILL,IWFILA,IRFILA,ISAVLO,
     &  IOPTIC,IGENFUN,IDISPER,IEMIT,IERZANA,IEMIAHW,
     &  IBHARD,IERZFUN,IRANDO,IBHTRACK,IBHELM,KBGENESIS,ISPLINE,
     &  IBSYM,IWLSOPT,IKBFORM,IRBTAB,NBTAB,IJUST,MYINUM,NSTEPMX,
     &  ICTEST ,IHFOLD,IBSYMY,IBSYMZ,
     &  NWMAX,ISPEC,IVELOFIELD,NDFREQ,NDOBSV,IFREQ2P,IWFILINT,JWFILINT,
     &  IHPIN,
     &  NDPAWC,IPIN,IPOLA,ifold,ibunch,ISPECANA,NGCOEF,ISPECMODE,
     &  NDMASHZ,NDMASHY,NDOBSVZ,NDOBSVY,ISIGUSR,ISPECINT,
     &  IPINALL,IHBOOK,IHINDEX,
     &  IHTRACK,IHTRSMP,IHTRACKM,IHBETA,IUNIT,IUNITS,IF1DIM,IHFREQ,
     &  IPOWER,NDPOL,IBEAMPOL,KUCROSS,KMAGSEQ,KMAGCOR,IMGSQF,
     &  IWBTAB,IABEND,irbmap6,iwbmap,
     &  IWFILFL0,IWFILFLF,IRPHI,
     &  IUSEM,IPINCIRC,ISTOKES,irbtabzy,ifourbtabzy,IRBTABXYZ,ISPECANAF,IBRILL,
     &  IWFILSTO,IWFLSTOF,IWFLSTOE,IWFLSTOEF,IRFILSP0,IRFILSTO,ISPECSUM,
     &  KELLIP,IWFILRAY,KELLANA,
     &  IPHASE,IDOSE,IPHOTON,IEFOLD,IDESYNC,ISPECDIP,IPHASEANA,
     &  IUOUT,IUNAME,IUSTEP,
     &  KBPOLYH,IGFLOAT
     &  ,KBPOLY3D,IWBPOLY3D
     &  ,KBPOLY2DH,IWBPOLY2DH,
     &  KBPharm,IWBpharm,
     &  IWFILS,IWFILSF,IWFILSE,IWFILSEF,
     &  IWFILB,IWFILBF,IWFILBE,IWFILBEF,
     &  IWFILBRILL,IWFILBRILLF,IWFILBRILLE,IWFILBRILLEF
     &  ,KBREC,KBPOLYMAG,IBATCH,kbundumag,kbundumap,kbunduverb
     &  ,IMAGSPLN,IHINPUT,IHOUTP,IMHBCOM, IMAGJOB
     &  ,IW_BLEN,IW_BLENF,IW_CIRC
     &  ,IHLIMIT_C,IHISINI_C,ihisascii,iroottrees,IBFORCE
     &  ,iampli,kampli,IAMPJIT,IUNDULATOR,IWIGGLER,IEXPERT,IBSUPER,IBERROR
     &  ,ieneloss,iefield,iroothdf5,iwarnbmap,iwarnmyb,mthreads
     &  ,CODE,CHISASCII


      NAMELIST/CONTRL/CODE,ECPHOTON,MYINUM,NSTEPMX,DMYENERGY,VXIN,VYIN,VZIN,BMOVECUT
     &  ,KBFELD,KHALBA,KHALBASY,KUNDUGAP,IRFILF,IRBTAB,
     &  KBEXTERN,KBAMWLS,IBGAUSS,KCIRC,IRPHI,
     &  xstart,XINTER,xstop,xianf,xiend,
     &  KSIGN,ICHECK,KBETAX,IFORM0,IFORM,
     &  IWFILB0,IRFILB0,IWFILF,IWSECTMAGS,IRFILP,IRFILB,ITRAKT,
     &  IWFILT0,IRFILT0,IWFILL0,GWINFC,BL0CUT,BL0HYS,
     &  IRFILL0,
     &  IEXPL0,NLPOI,IWFILL,IWFILA,IRFILA,ISAVLO,IOPTIC,
     &  IBHARD,IERZFUN,IERZANA,IGENFUN,
     &  IRANDO,IBHTRACK,IBHELM,KBGENESIS,ISPLINE,IDISPER,
     &  IBSYM,XBSYM,IWLSOPT,IKBFORM,IJUST,IBSYMY,IBSYMZ
     &  ,YSTART,ZSTART,DMYCUR,BANWID
     &  ,ICTEST,IEMIT,IEMIAHW,IHFOLD
     &  ,ISPEC,IVELOFIELD,IWFILSP0,IFREQ2P,IWFILINT,JWFILINT,IWFILSPF
     &  ,IWFILPOW
     &  ,IHPIN,IPOLA,ifold,ibunch,IPIN,ISPECANA,ISIGUSR,ISPECINT,ISPECMODE
     &  ,IPINALL,IHINDEX
     &  ,IHTRACK,IHTRSMP,IHTRACKM,IHBETA,IUNIT,IUNITS,IF1DIM,IHFREQ
     &  ,XSTARTH,XSTOPH,IPOWER,IBEAMPOL,KUCROSS,KMAGSEQ,KMAGCOR,IMGSQF,
     &  IWBTAB,irbmap6,iwbmap
     &  ,IWFILFL0,IWFILFLF
     &  ,IUSEM,IPINCIRC,ISTOKES,irbtabzy,ifourbtabzy,IRBTABXYZ,ISPECANAF,IBRILL
     &  ,IWFILSTO,IWFLSTOF,IWFLSTOE,IWFLSTOEF,IRFILSP0,IRFILSTO,ISPECSUM
     &  ,KELLIP,IWFILRAY,KELLANA
     &  ,IPHASE,IDOSE,IPHOTON,IEFOLD,IDESYNC,ISPECDIP,IPHASEANA
     &  ,IUOUT,IUNAME,IUSTEP
     &  ,KBPOLYH
     &  ,KBPOLY3D,IWBPOLY3D
     &  ,KBPOLY2DH,IWBPOLY2DH,
     &  KBPharm,IWBpharm,
     &  IWFILS,IWFILSF,IWFILSE,IWFILSEF,
     &  IWFILB,IWFILBF,IWFILBE,IWFILBEF,
     &  IWFILBRILL,IWFILBRILLF,IWFILBRILLE,IWFILBRILLEF
     &  ,KBREC,KBPOLYMAG,kbundumag,kbundumap,kbunduverb
     &  ,IMAGSPLN,IHINPUT,IHOUTP,IMHBCOM, ihisascii,iroottrees,
     &  ieneloss,iefield,iroothdf5,
     &  iampli,kampli,IAMPJIT,IUNDULATOR,IWIGGLER,IEXPERT,IBSUPER,IBERROR,ibforce,
     &  nocern,iadjust,mthreads,
     &  CHISASCII
*KEEP,CMPARA.

      INTEGER LIDIMP,NOMDIMP,IBFDIM4P,IBFDIM2P,NXPANP,NYPANP
      INTEGER NBTABP,NDMASHZP,NDMASHYP,MAXFOUR,NFOURD

      INTEGER NWMAXP,NDFREQP,NDOBSVP,NDARGUP,NDWSOUP
      INTEGER NGCOEFP,NDOBSVZP,NDOBSVYP,NSPLINEP,NDPOLP,NDSPARP

      INTEGER N3DPOIP,N2DHPOIP,NPHPOIP


      PARAMETER (LIDIMP=501)    ! MAX. NUMBER OF SOURCES
      PARAMETER (NDPOLP=101)    ! MAX. NUMBER OF POLES
                                ! IN SR BEAMPOW POLES MAY BE SPLITTED, I.E.
                                ! NUMBER OF POLES ARE NOT NUMBER OF
                                ! HARDWAREPOLES
      !
      PARAMETER (NWMAXP=2**15)    !NUMBER OF POINTS OF REFERENCE ORBIT
      PARAMETER (NDFREQP=1100001)    !NUMBER OF FREQUENCES FOR SPECTRUM-CALCULATION
      PARAMETER (NDSPARP=1024)   !TO HAVE SOME SPARE IN BUFFER
      PARAMETER (NDWSOUP=NDSPARP+1024)!NUMBER OF STEPS PER SOURCE OF
                                      !(MINI-TRAJEKTORY)
               !SEE ALSO PARAMETER NBADDP IN SOURCE.CMN
               !FOR INTEGRATION BUFFER IN SR SPECTRUM
      !
      PARAMETER (NDARGUP=NDSPARP+1024)!NUMBER OF INTEGRATION STEPS PER SOURCE
                                      !MUST BE LOWER OR EQUAL NDWSOUP
      !
      PARAMETER (NDOBSVZP=2048)    !NUMBER OF OBSERVATION POINTS IN Z-DIRECTION
      ! SAME FOR Z AND Y, OR PROBLEMS...
      PARAMETER (NDOBSVYP=NDOBSVZP)    !NUMBER OF OBSERVATION POINTS IN Y-DIRECTION
      PARAMETER (NDOBSVP=NDOBSVZP*NDOBSVYP) !NUMBER OF OBSERVATION POINTS
      PARAMETER (NSPLINEP=NDOBSVZP+NDOBSVYP)!FOR SR FSPLINE

      PARAMETER (NGCOEFP=32)         !NUMBER FOURIER COEFFICIENT FOR GAUSSIAN FOR
      !                                !FOLDING PROCEDURE
      PARAMETER (NDMASHZP=NDOBSVZP/2)   !NUMBER OF ADJACENT MASHES FOR FOLDING
      PARAMETER (NDMASHYP=NDOBSVYP/2)   !NUMBER OF ADJACENT MASHES FOR FOLDING

      PARAMETER(MAXFOUR=2**15)  !NUMBER OF FOURIER COEFFICIENTS FOR B-FIELD
      PARAMETER (NFOURD=2*MAXFOUR) !NUMBER OF FOURIER COEFFICIENTS FOR SR FOURWLS

      INTEGER NBMESSXP,NBMESSYP,NBMESSZP
      PARAMETER (NBMESSXP=3,NBMESSYP=3,NBMESSZP=3)

      PARAMETER(N3DPOIP=NBMESSXP*NBMESSYP*NBMESSZP) !NUMBER DATA POINTS FOR BPOLY3D
      PARAMETER(N2DHPOIP=NBMESSXP*NBMESSYP*NBMESSZP) !NUMBER DATA POINTS FOR BPOLY3D
      PARAMETER(NPHPOIP=NBMESSXP*NBMESSYP*NBMESSZP) !NUMBER DATA POINTS FOR BPOLY3D

      INTEGER NLIOBFRP,NOBFRP,NLIFRP,NLIOBZP,NLIOBP
      INTEGER ILIOB,ILIOBFR,IOBFR,ILIOBZ,ILIFR,IFROB
        PARAMETER (NLIOBFRP=600000)  !GENERAL DIMENSION OF SPECTRUM ARRAYS
      PARAMETER (NLIOBP=NLIOBFRP)
      PARAMETER (NLIOBZP=NLIOBFRP)
      PARAMETER (NOBFRP=NLIOBFRP)
      PARAMETER (NLIFRP=NLIOBFRP)

C------------ OLD STUFF (??) --------------------------------

      PARAMETER (NOMDIMP=1)   ! MAX. ANZAHL VON FREQUENZEN IM SPEKTRUM
      PARAMETER (IBFDIM4P=1)    ! BUFFER GROESSE FUER RBUFF4,IBUFF4
      PARAMETER (IBFDIM2P=8)    ! BUFFER GROESSE FUER RBUFF2
      PARAMETER (NXPANP=1)      ! PANDIRA X-DIMENSION
      PARAMETER (NYPANP=1)      ! PANDIRA Y-DIMENSION
      PARAMETER (NBTABP=2**14+2**13)   ! BTAB DIMENSION

c20180509      REAL*4 RBUFF4(4,IBFDIM4P)
c      REAL*4 RBUFF2(2,IBFDIM2P)
c      INTEGER IBUFF4(4,IBFDIM4P)
c      INTEGER IBUFF2(2,IBFDIM2P)
c      EQUIVALENCE (RBUFF4(1,1),IBUFF4(1,1)),(RBUFF2(1,1),IBUFF2(1,1))
c      COMMON/BUFCOM/RBUFF4,RBUFF2,ILIOB,ILIOBFR,IOBFR,ILIOBZ,ILIFR,IFROB
*KEEP,TRACK.
      INTEGER NCO,MCO,IBYONLY,ITRACK

      DOUBLE PRECISION PHIX,PHIMX,PHIMN
     &  ,XMX,XMN,YMX,YMN,ZMX,ZMN
     &  ,BXMX,BXMN,BYMX,BYMN,BZMX,BZMN
     &  ,XMXAE,XMNAE,YMXAE,YMNAE,ZMXAE,ZMNAE
     &  ,BXMXAE,BXMNAE,BYMXAE,BYMNAE,BZMXAE,BZMNAE
     &  ,BINT0,PINT,tint
     &  ,BINT1X,BINT1Y,BINT1Z,BINT2X,BINT2Y,BINT2Z,BINT3Y,BINT3YA
     &  ,DTIM0,DS0
     &  ,B2INTY
     &  ,WTRA2I,TTRA2I,HTRA2I,WTRA2IC,
     &  XTRACK,YTRACK,ZTRACK,
     &  VXTRACK,VYTRACK,VZTRACK

      COMMON/MINMAXC/
     &  PHIX,PHIMX,PHIMN,XMX,XMN,YMX,YMN,ZMX,ZMN
     &  ,BXMX,BXMN,BYMX,BYMN,BZMX,BZMN
     &  ,XMXAE,XMNAE,YMXAE,YMNAE,ZMXAE,ZMNAE
     &  ,BXMXAE,BXMNAE,BYMXAE,BYMNAE,BZMXAE,BZMNAE
     &  ,BINT0,PINT,tint
     &  ,BINT1X,BINT1Y,BINT1Z,BINT2X,BINT2Y,BINT2Z,BINT3Y,BINT3YA
     &  ,DTIM0,DS0
     &  ,WTRA2I,TTRA2I,HTRA2I,WTRA2IC
     &  ,B2INTY
     &  ,XTRACK,YTRACK,ZTRACK
     &  ,VXTRACK,VYTRACK,VZTRACK
     &  ,NCO,MCO,IBYONLY,ITRACK
*KEEP,TRACK0.
      DOUBLE PRECISION
     &  X0,Y0,Z0,VX0,VY0,VZ0,t0track,tftrack,
     &  XF0,YF0,ZF0,VXF0,VYF0,VZF0,
     &  YIANF,ZIANF,YPIANF,ZPIANF,
     &  YIEND,ZIEND,YPIEND,ZPIEND

      COMMON/TRACK0C/
     &  X0,Y0,Z0,VX0,VY0,VZ0,t0track,tftrack,
     &  XF0,YF0,ZF0,VXF0,VYF0,VZF0,
     &  YIANF,ZIANF,YPIANF,ZPIANF,
     &  YIEND,ZIEND,YPIEND,ZPIEND
*KEEP,SPECT.

      INTEGER NPWALL,NPOLMX

      COMPLEX*16 VPOLA(3),VSTOKES(4,3)
      COMPLEX*16 REFLEC(3)

      DOUBLE PRECISION SPECNOR,POWNOR

      DOUBLE PRECISION SPECPOWVHT

      DOUBLE PRECISION PINDOS
      DOUBLE PRECISION WFLUXTI,WFLUXTIF,SPECTOTMX(6),WALL(2)
     &  ,POWBCUT,XWALLI,XWALLE
     &  ,POWCOR,XABSORB,ZABSORB(2)

      REAL*4 TOTGAM(6),TOTMAX(12)

      REAL*4  STOKCMX(4,2),G3CMX(2)
     &  ,STOKCMXF(4,2),G3CMXF(2)
     &  ,STOKCMXE(4,2),G3CMXE(2)
     &  ,STOKCMXEF(4,2),G3CMXEF(2)
     &  ,BRILLCMX(12,2),B3CMX(2)
     &  ,BRILLCMXF(12,2),B3CMXF(2)
     &  ,BRILLCMXE(12,2),B3CMXE(2)
     &  ,BRILLCMXEF(12,2),B3CMXEF(2)
     &  ,WSTOKMX(4,2),WG3MX(2)
     &  ,WSTOKMXF(4,2),WG3MXF(2)
     &  ,WSTOKMXE(4,2),WG3MXE(2)
     &  ,WSTOKMXEF(4,2),WG3MXEF(2)
     &  ,STOKESMAX(4,4),STOKESMAXF(4,4)
     &  ,STOKESMAXE(4,4),STOKESMAXEF(4,4)

      COMMON/SPECTC/
     &   VPOLA,VSTOKES,REFLEC
     &  ,SPECNOR,POWNOR
     &  ,SPECPOWVHT
     &  ,PINDOS
     &  ,WFLUXTI
     &  ,WFLUXTIF,SPECTOTMX
     &  ,WALL,POWBCUT,XWALLI,XWALLE
     &  ,POWCOR,XABSORB,ZABSORB
     &  ,TOTGAM,TOTMAX
     &  ,STOKCMX,G3CMX
     &  ,STOKCMXF,G3CMXF
     &  ,STOKCMXE,G3CMXE
     &  ,STOKCMXEF,G3CMXEF
     &  ,BRILLCMX,B3CMX
     &  ,BRILLCMXF,B3CMXF
     &  ,BRILLCMXE,B3CMXE
     &  ,BRILLCMXEF,B3CMXEF
     &  ,WSTOKMX,WG3MX
     &  ,WSTOKMXF,WG3MXF
     &  ,WSTOKMXE,WG3MXE
     &  ,WSTOKMXEF,WG3MXEF
     &  ,STOKESMAX,STOKESMAXF
     &  ,STOKESMAXE,STOKESMAXEF
     &  ,NPWALL,NPOLMX


      NAMELIST/SPECTN/
     &        VPOLA,REFLEC
     &        ,WALL,POWBCUT,XWALLI,XWALLE,NPWALL,POWCOR,XABSORB
     &        ,ZABSORB,NPOLMX
*KEEP,OBSERV.


      DOUBLE PRECISION PINCEN(3),PINW,PINH,pinr,pinrad,
     &  OBSVDZ,OBSVDY,OBS1X,OBS1Y,OBS1Z,OBSVDR,OBSVDPHI
     &  ,pinhsc,pinwsc,rpinsph

      INTEGER NOBSV,NOBSVZ,NOBSVY,MPINZ,MPINY,MPINR,MPINPHI
     &  ,mpinyorig,mpinzorig
      INTEGER MOBSV,MOBSVZ,MOBSVY,MEDGEZ,MEDGEY
      INTEGER MMEDGEZ,MMEDGEY,IRFILOB,MEDGER
     &  ,IPBRILL,ICBRILL
     &  ,NOBSVRPHI,NOBSVR,NOBSVPHI
     &  ,MOBSVRPHI,MOBSVR,MOBSVPHI,IQUADPHI

      COMMON/OBSERV/OBSVDZ,OBSVDY,OBS1X,OBS1Y,OBS1Z
     &  ,PINCEN,PINW,PINH,pinr,pinrad,OBSVDR,OBSVDPHI
     &  ,pinhsc,pinwsc
     &  ,rpinsph
     &  ,NOBSV,NOBSVZ,NOBSVY,MPINZ,MPINY,MPINR,MPINPHI
     &  ,mpinyorig,mpinzorig
     &  ,MOBSV,MOBSVZ,MOBSVY,MEDGEZ,MEDGEY
     &  ,MMEDGEZ,MMEDGEY,IRFILOB,MEDGER
     &  ,NOBSVRPHI,NOBSVR,NOBSVPHI
     &  ,MOBSVRPHI,MOBSVR,MOBSVPHI
     &  ,IPBRILL,ICBRILL,IQUADPHI

      NAMELIST/PINHOLE/PINCEN,MPINZ,MPINY,MPINR,MPINPHI,OBSVDR,OBSVDPHI,
     &  PINW,PINH,pinr,pinrad,MEDGEZ,MEDGEY
     &  ,MMEDGEZ,MMEDGEY,IRFILOB,OBS1X,OBS1Y,OBS1Z,OBSVDZ,OBSVDY
     &  ,IPBRILL,IQUADPHI
     &  ,pinhsc,pinwsc
     &  ,rpinsph
*KEEP,FREQS.
      CHARACTER(65) ABSCOM,EFFCOM

      INTEGER NFREQ,NINTFREQ,IFILTER,IFILMUL,IEFFI,IHFIL
     &         ,NFREQEP,NFREQEM
     &         ,NFREQ0,NFREQ0M,NFREQ0P

C260194 {
      DOUBLE PRECISION WELLEN(NDFREQP),WELLENC,WELLENCF
C260194 }

      DOUBLE PRECISION FREQ(NDFREQP),ABSMU(NDFREQP),ABSMUTOT(NDFREQP),
     &  FREQLOW,FREQHIG,ABSTHI,ABSDEN
      DOUBLE PRECISION EXPMU(NDFREQP),FREQC,FREQCF,SPECCUT
     &        ,ABSMUEN(NDFREQP),AREAM2,FRSCALE,EFF(NDFREQP)

      COMMON/FREQSC/
     &         WELLEN,WELLENC,WELLENCF
     &        ,FREQ,ABSMU,ABSMUTOT,FREQLOW,FREQHIG,ABSTHI,ABSDEN
     &        ,EXPMU,FREQC,FREQCF,SPECCUT
     &        ,ABSMUEN,AREAM2,FRSCALE,EFF
     &        ,NFREQ,NINTFREQ,IFILTER,IFILMUL,IEFFI,IHFIL
     &        ,NFREQEP,NFREQEM
     &        ,NFREQ0,NFREQ0M,NFREQ0P
     &        ,ABSCOM,EFFCOM

      NAMELIST/FREQN/FREQLOW,FREQHIG,NINTFREQ,ABSTHI,AREAM2
     &               ,IHFIL,IFILTER,IFILMUL,IEFFI,FREQC,FREQCF,SPECCUT,FRSCALE
*KEEP,SOURCEF90.

      INTEGER NBADDP,NROIP
      PARAMETER (NBADDP=100,NROIP=512)
      INTEGER NROI,NROIA,NIDSOURCE,NSOURCE,NDWSOU,NLPOIO,
     &          ISOURO,NSADD,NBUFF,NDSPAR,IROIASYEXP(NROIP)

      DOUBLE PRECISION ROIX(NROIP),ROIP(NROIP)

      COMMON/SOURCEC/ROIX,ROIP
     &,NROI,NROIA,NIDSOURCE,NSOURCE,NDWSOU,NLPOIO,ISOURO,NSADD,NBUFF,NDSPAR
     &,IROIASYEXP

      NAMELIST /ROIN/ NROI,ROIX,ROIP,IROIASYEXP
*KEEP,BERROR.

      INTEGER NBERROR,IBERRSEED,NBERRMOD,ICUTFIBO

      DOUBLE PRECISION B0ERROR,XCENERR,
     &  XLENERR,YLENERR,ZLENERR,
     &  XKERROR,YKERROR,ZKERROR,
     &  ETAFIBO,resrms

      COMMON/BERRORM/
     &  B0ERROR,XCENERR,
     &  XLENERR,YLENERR,ZLENERR,
     &  XKERROR,YKERROR,ZKERROR,
     &  ETAFIBO,resrms,
     &  NBERROR,IBERRSEED,NBERRMOD,ICUTFIBO

      NAMELIST/BERRORN/B0ERROR,XLENERR,XCENERR,ZLENERR,NBERROR,IBERRSEED
     &  ,NBERRMOD,ETAFIBO,ICUTFIBO

*KEEP,AMPLI.

      INTEGER IAMPDIMP
      PARAMETER (IAMPDIMP=10000)

      INTEGER IMAMPLI,IAMPSKIP,IAMPTERM,IAMPREAD,modeph
     &  ,IAMPOBSV,IAMPCOMP,IAMPREP,IAMPSUP,IAMPSEED,iamppin,iamppincirc
     &  ,iampcoh,iampincoh,nampbunchharm,noemitph,noespreadph,mampthreads

      DOUBLE PRECISION AMPFREQ,ampr2corr,AMPPHI(IAMPDIMP),AMPSHIFT(IAMPDIMP)
     &  ,AMPSCALE(IAMPDIMP),AMPRAN,FACAMPLI,phrERROR,
     &  phrshift,phrb0h,phrb0v,phrperl,phdx,phdy,phdz,phrxbeta,
     &  phrbetah,phralphah,phrbetav,phralphav,phrespread,phremith,phremitv,
     &  ampcohsig,ampbunchlen,ampbunchcharge,ampbunchp0,ampbunchr56,
     &  phrdisph,phrdispph,phrdispv,phrdisppv,phrbunlen

      COMMON/AMPLIC/
     &  ampfreq,ampr2corr,AMPPHI,AMPSHIFT,AMPSCALE,AMPRAN,FACAMPLI,phrERROR
     &  ,ampcohsig,ampbunchlen,ampbunchcharge,ampbunchp0,ampbunchr56,phrxbeta,
     &  phrshift,phrb0h,phrb0v,phrperl,phdx,phdy,phdz,
     &  phrbetah,phralphah,phrbetav,phralphav,phrespread,phremith,phremitv,
     &  phrdisph,phrdispph,phrdispv,phrdisppv,phrbunlen,
     &  IMAMPLI,IAMPSKIP,IAMPTERM,IAMPREAD,modeph
     &  ,IAMPOBSV,IAMPCOMP,IAMPREP,IAMPSUP,IAMPSEED,iamppin,iamppincirc
     &  ,iampcoh,iampincoh,nampbunchharm,noemitph,noespreadph,mampthreads

      NAMELIST/AMPLIN/
     &  IMAMPLI,IAMPSKIP,IAMPTERM,IAMPREAD
     & ,IAMPCOMP,IAMPREP
     & ,AMPSHIFT,AMPSCALE,ampfreq,ampr2corr,AMPPHI,IAMPSUP,AMPRAN,IAMPSEED
     &  ,ampcohsig,ampbunchlen,ampbunchcharge,ampbunchp0,ampbunchr56
     &  ,iampcoh,iampincoh,nampbunchharm

      NAMELIST/PHASEREPN/phrERROR,noemitph,noespreadph,modeph,phrxbeta,
     &  phrshift,phrperl,phrb0h,phrb0v,phdx,phdy,phdz,
     &  phrdisph,phrdispph,phrdispv,phrdisppv,phrbunlen,
     &  phrbetah,phralphah,phrbetav,phralphav,phrespread,phremith,phremitv
*KEEP,PHYCON.
      DOUBLE PRECISION
     &  CLIGHT1,CGAM1,CQ1,alpha1,
     &  dnull1,done1,sqrttwopi1,
     &  EMASSG1,EMASSE1,ECHARGE1,EMASSKG1,EPS01,ERAD1,
     &  GRARAD1,
     &  HBAR1,HBAREV1,HPLANCK1,
     &  PI1,POL1CON1,POL2CON1,
     &  RADGRA1,rmu01,rmu04pi1,
     &  TWOPI1,HALFPI1,
     &  WTOE1,gaussn1,cK934,powcon1,ecdipev1,ecdipkev1

      COMMON/PHYCON1/
     &  CLIGHT1,CGAM1,CQ1,alpha1,
     &  dnull1,done1,sqrttwopi1,
     &  EMASSG1,EMASSE1,ECHARGE1,EMASSKG1,EPS01,ERAD1,
     &  GRARAD1,
     &  HBAR1,HBAREV1,HPLANCK1,
     &  PI1,POL1CON1,POL2CON1,
     &  RADGRA1,rmu01,rmu04pi1,
     &  TWOPI1,HALFPI1,
     &  WTOE1,gaussn1,cK934,powcon1,ecdipev1,ecdipkev1
*KEEP,WAVEENV.
      integer, parameter :: maxinstp=100
      integer iwstat(maxinstp),iwinstance,nwinstances,nwgood
      integer kpython

      character(32) chplatform, chrmtree, chrmdir,chrmfile,chmkdir,chcpfile,
     &  chcptree,chmvfile
      character(1024) chpythonpath,chhostname,chcompiler,chcwd,chwavepath,
     &  chpythoncom,chuserhome,chwavehome,chwavedir,chuser,chwstage,
     &  chpythonhome
      character chpathsep

      common/waveenvc/
     &  iwstat,iwinstance,nwinstances,nwgood,kpython,
     &  chplatform, chrmtree, chrmdir,chrmfile,chmkdir,chcpfile,
     &  chcptree,chmvfile,chpythonpath,chhostname,chcompiler,chcwd,chwavepath,
     &  chpythoncom,chuserhome,chwavehome,chwavedir,chuser,chwstage,
     &  chpythonhome,chpathsep


      namelist/platformn/ chpythonhome,
     &  chplatform, chrmtree, chrmdir,chrmfile,chmkdir,chcpfile,chcptree,
     &  chmvfile,chpathsep,chwavepath,chpythoncom

*KEEP,USERVAR.
*
*     USER NAMELIST
*
      DOUBLE PRECISION UDUM

      DOUBLE PRECISION USER(1000)
      DOUBLE PRECISION ULOOP(1000)

      INTEGER IUDUM
      CHARACTER(128) CUDUM
      CHARACTER(128) userchar(1000)

      COMMON/USERC/USER,ULOOP,UDUM,IUDUM,CUDUM,userchar

      NAMELIST/USERN/USER,UDUM,IUDUM,CUDUM,userchar
*KEND.


      return
      end
