*CMZ :  2.15/00 28/04/2000  10.34.14  by  Michael Scheer
*CMZ :  1.01/00 29/10/97  12.32.45  by  Michael Scheer
*-- Author :    Michael Scheer   29/10/97

      PROGRAM WAVE_LOOP

      IMPLICIT NONE

      CHARACTER*60 RFILE,VFILE,UFILE

      INTEGER LUNRES,LUNVAR,LUNU,IVAR,ITRY

      INTEGER ILOOP,JLOOP,NLOOP(2),ICODE

      DOUBLE PRECISION VAR(2),VARMIN(2),VARMAX(2),DVAR(2)

      INTEGER NFREQP,I
      PARAMETER(NFREQP=33)
      REAL*4 PHASE,FREQ(NFREQP),SPEC(NFREQP)

      DATA LUNU/19/
      DATA UFILE/'UOUT.LOOP'/ !DUMMY TO PASS VARIABLES TO WAVE_LOOP

      DATA LUNVAR/20/
      DATA VFILE/'UNAME.LOOP'/ !DUMMY TO PASS VARIABLES TO WAVE

      DATA LUNRES/21/
      DATA RFILE/'WAVE.LOOP'/    !FILE OF RESULTS

      READ(5,*)NLOOP(1),VARMIN(1),VARMAX(1)
      READ(5,*)NLOOP(2),VARMIN(2),VARMAX(2)

      OPEN(UNIT=LUNVAR,FILE=VFILE,STATUS='NEW',FORM='FORMATTED')
      CLOSE(LUNVAR)

      OPEN(UNIT=LUNVAR,FILE='TERM.LOOP',STATUS='NEW',FORM='FORMATTED')
      CLOSE(LUNVAR)

      OPEN(UNIT=LUNRES,FILE=RFILE,STATUS='NEW',FORM='FORMATTED',
     &     RECL=256)
      CLOSE(LUNRES)

      DO IVAR=1,2
        IF (NLOOP(IVAR).GT.1) THEN
             DVAR(IVAR)=(VARMAX(IVAR)-VARMIN(IVAR))/(NLOOP(IVAR)-1)
        ELSE
          DVAR(IVAR)=0.0
        ENDIF
      ENDDO !ILOOP

      DO ILOOP=1,NLOOP(1)

      VAR(1)=(VARMIN(1)+DVAR(1)*(ILOOP-1))

      DO JLOOP=1,NLOOP(2)

          VAR(2)=(VARMIN(2)+DVAR(2)*(JLOOP-1))

          OPEN(UNIT=LUNVAR,FILE=VFILE,STATUS='OLD',FORM='FORMATTED')
         WRITE(LUNVAR,*)VAR(2)
          CLOSE(LUNVAR)

          CALL LIB$SPAWN('$PURGE/KEEP=10 WAVE.OUT,WH:WAVE_HISTO.HIS')
          CALL LIB$SPAWN('$RUN/NODEBUG WE:WAVE')

          OPEN(UNIT=LUNU,FILE='TERM.LOOP',STATUS='OLD',ERR=9999)
          CLOSE(LUNU)

          OPEN(UNIT=LUNU,FILE=UFILE,STATUS='OLD')
         READ(LUNU,*)ICODE,PHASE
         DO I=1,NFREQP
             READ(LUNU,*)FREQ(I),SPEC(I)
         ENDDO
99           CLOSE (LUNU)

        ITRY=0
999     CALL LIB$SPAWN('$WAIT 00:00:05')
        ITRY=ITRY+1
        IF (ITRY.GT.100) GOTO 9999

          OPEN(UNIT=LUNRES,FILE=RFILE,STATUS='OLD',ACCESS='APPEND'
     &   ,FORM='FORMATTED',RECL=256,ERR=999)
            WRITE(LUNRES,*)ICODE,VAR,NFREQP
         DO I=1,NFREQP
              WRITE(LUNRES,*)FREQ(I),SPEC(I)
         ENDDO
          CLOSE(LUNRES)

          WRITE(6,*)
          WRITE(6,*) 'NUMBER OF LOOPS DONE:',ILOOP,JLOOP
C          WRITE(6,*)ICODE,VAROUT
          WRITE(6,*)

      ENDDO !JLOOP
      ENDDO !ILOOP

      WRITE(6,*)
      WRITE(6,*)'--- Program WAVE_LOOP terminated ---'
      WRITE(6,*)

      STOP ' '

9999  STOP '--- Program WAVE_LOOP aborted ---'

      END
